// r4dx::server::ReasoningSplitter -- splits a model's raw generated text at the first "</think>"
// close tag into a reasoning span and an answer span (the DeepSeek/vLLM `reasoning_content`
// convention, docs/server.md's "reasoning_content" section). Pure text state machine, no HIP/
// r4dx::model dependency, so it is unit-testable on CPU alone
// (tests/server/test_reasoning_splitter.cpp), exactly like response_sink.h/openai_types.h.
//
// The model's own opening "<think>\n" is part of the PROMPT's generation preamble, never generated
// text (engine.cpp only ever turns thinking on/off via `enable_thinking`, which controls whether
// the prompt ends with an open or a pre-closed think block -- see chat_template.h) -- so this class
// never scans for an opening tag, only the closing one, and starts in `Mode::kReasoning`
// unconditionally.
//
// One instance is fed EITHER piece-by-piece as generation proceeds (Tokenizer::StreamDecoder::
// push's return value, response_sink.h's OnToken contract) OR the entire buffered generation in a
// single Push() call (engine.cpp's tool-call-mode whole-buffer split, RunRequest's `tool_mode`
// block) -- the same state machine serves both, so the splitting logic lives in exactly one place
// rather than being smeared across BufferingSink/StreamingSink/Engine::RunRequest.
//
// Byte-exact holdback: at most `strlen("</think>") - 1 == 7` bytes are ever held back between
// Push() calls (the longest possible proper prefix of "</think>"), flushed the instant they can no
// longer extend into a match. Since "</think>" is pure ASCII and every UTF-8 continuation/lead byte
// of a multi-byte character has its high bit set (>= 0x80), no substring of "</think>" can ever be
// confused with part of a multi-byte character -- so this holdback boundary always falls on a
// UTF-8 character boundary as long as every `piece` passed in already does (Tokenizer::
// StreamDecoder's own contract). Multi-byte content on either side of the tag is therefore never
// split mid-character.
//
// Trimming policy (deliberately asymmetric -- see docs/server.md): this class only ever (a) strips
// the "</think>" tag itself and (b) skips blank lines (a run of '\n'/'\r') immediately following
// it, so streaming reasoning_content/content deltas concatenate back to the untrimmed source text
// exactly except for that one boundary. It does NOT trim leading/trailing whitespace off the
// reasoning span itself -- callers that want the non-streaming "trim the whole span" behavior
// (openai_types.h's message.reasoning_content) do that once, themselves, on the concatenation of
// every kReasoning event (see BufferingSink::OnDone / Engine::RunRequest's tool_mode block).
#pragma once

#include <cstddef>
#include <string>
#include <vector>

namespace r4dx::server {

// Per-dialect reasoning markers (dialect.h owns the table). The default is Qwen's: no opener is ever
// scanned for (it is part of the prompt), the close tag is "</think>", and blank lines right after
// the close tag are dropped.
struct ReasoningSyntax {
  // Text the model itself generates to open a reasoning span. Only consulted in StartState::
  // kExpectOpener (Gemma 4: "<|channel>thought\n"); empty for Qwen.
  std::string open;
  std::string close = "</think>";
  // Drop a run of '\n'/'\r' immediately after the close tag (ReasoningSplitter's policy above).
  bool skip_blank_after_close = true;
};

class ReasoningSplitter {
 public:
  // One classified fragment of a Push()/Finish() call's input. `is_reasoning` tags which half of
  // the split this text belongs to; a single Push() call can return 0, 1, or 2 events (2 only when
  // one piece itself straddles the close tag: the reasoning tail, then the answer head).
  struct Event {
    bool is_reasoning;
    std::string text;
  };

  // kExpectOpener is the pre-decision state of StartState::kExpectOpener (never reported once the
  // opener matched or diverged).
  enum class Mode { kReasoning, kAnswer, kExpectOpener };

  // Where the generation starts. kInReasoning: the prompt already opened the span (Qwen `<think>\n`,
  // Gemma after a tool response with thinking on). kExpectOpener: the model may or may not open a
  // span itself (Gemma thinking on, first generated bytes); bytes are held only while they are a
  // proper prefix of `syntax.open`, a full match enters reasoning, a divergence releases the held
  // bytes as ANSWER text and the rest of the generation is answer. kAnswer: no reasoning at all.
  enum class StartState { kInReasoning, kExpectOpener, kAnswer };

  ReasoningSplitter() = default;
  explicit ReasoningSplitter(ReasoningSyntax syntax, StartState start = StartState::kInReasoning);

  Mode mode() const { return mode_; }

  // Feeds the next piece of raw generated text. Returns zero or more classified events, already
  // stripped of the "</think>" tag itself and (answer side only) any blank lines immediately
  // following it. Once `mode()` has become kAnswer, every subsequent Push() is a pure passthrough
  // (no tag re-scanning) -- a literal "</think>" appearing in the real answer text is not
  // special-cased, matching tool_call_parser.h's own note that this checkpoint's generated text
  // carries at most one such tag.
  std::vector<Event> Push(const std::string& piece);

  // Call once after the last Push(): flushes whatever is still held back internally. If the close
  // tag was never seen (`mode() == kReasoning`), the held bytes are genuine trailing reasoning text
  // (they could not have matched "</think>", or Push would already have consumed them) -- this is
  // the "never-closed" case (docs/server.md: content stays empty, everything generated is
  // reasoning). If the tag WAS seen, any held bytes can only be from the leading-blank-line skip
  // (generation ended entirely inside the blank lines right after the tag) and are correctly
  // dropped, never surfaced as content.
  std::vector<Event> Finish();

 private:
  void ProcessAnswer(const std::string& buf, std::vector<Event>& events);

  ReasoningSyntax syntax_;
  Mode mode_ = Mode::kReasoning;
  std::string tag_hold_;         // reasoning-side: bytes that could still extend into the close tag
  std::string nl_hold_;          // answer-side: leading blank-line bytes not yet ruled final
  bool answer_started_ = false;  // true once a non-newline answer byte has been emitted
  bool skip_blank_ = false;      // answer side follows a close tag: drop leading blank lines
};

// Locates, inside the engine's whole-generation `accumulated` text, where the reasoning span ends
// and the answer begins -- the CPU-testable replacement for engine.cpp's literal "</think>" / `+ 8`
// bookkeeping (NoteReasoningProgress / FlushGated). It is a pure function of the text seen so far, so
// Update() may be called with the growing string after every token (idempotent once resolved).
//
//   * kInReasoning start: reasoning until `close` appears; reasoning_end() = offset after the tag.
//   * kExpectOpener start: undecided while `accumulated` is a proper prefix of `open`; on a match
//     behaves as kInReasoning (the opener bytes count as part of the reasoning span); on divergence
//     the whole generation is answer (reasoning_end() == 0, no blank-line skip).
//   * kAnswer start: answer from byte 0.
class ReasoningLocator {
 public:
  enum class State { kPending, kReasoning, kAnswer };

  ReasoningLocator(ReasoningSyntax syntax, ReasoningSplitter::StartState start);

  void Update(const std::string& accumulated);

  State state() const { return state_; }
  // True while the generated text so far is (or may still turn into) reasoning.
  bool reasoning_open() const { return state_ != State::kAnswer; }
  // Offset in `accumulated` of the first byte after the reasoning span (after the close tag); 0 when
  // there was no reasoning at all; npos until state() == kAnswer.
  size_t reasoning_end() const { return end_; }
  // Offset of the first ANSWER byte the sink-level ReasoningSplitter will emit, i.e. reasoning_end()
  // plus the blank-line skip after a real close tag; npos while that is unknown (state != kAnswer,
  // or only blank lines have arrived so far, `limit` being the number of usable bytes).
  size_t AnswerBegin(const std::string& accumulated, size_t limit) const;

 private:
  ReasoningSyntax syntax_;
  State state_;
  size_t end_;
  bool closed_by_tag_ = false;
};

// Trims leading/trailing ASCII whitespace (space, tab, '\n', '\r') -- the non-streaming
// `message.reasoning_content` trim rule (docs/server.md's "reasoning_content" section, task item
// 5a). Exposed here, rather than folded into BufferingSink, because Engine::RunRequest's
// tool-call-mode one-shot split (RunRequest's `tool_mode` block) needs the exact same trim applied
// to the exact same concatenation-of-kReasoning-events text that BufferingSink::OnDone produces.
std::string TrimReasoningWhitespace(const std::string& s);

}  // namespace r4dx::server
