// r4dx::server::ResponseSink -- what the Engine's worker thread (engine.cpp, HIP-dependent, not
// built by this header) drives per request, decoupled from whether the HTTP layer is serving it
// as one-shot JSON or an SSE stream. Both concrete sinks below are pure CPU/string-formatting
// code (openai_types.h + sse.h + request_queue.h), so this header and its .cpp are unit-testable
// without a GPU (tests/server/test_response_sink.cpp).
#pragma once

#include <atomic>
#include <condition_variable>
#include <cstdint>
#include <mutex>
#include <optional>
#include <string>

#include <vector>

#include "nlohmann/json.hpp"
#include "openai_types.h"
#include "reasoning_splitter.h"
#include "request_queue.h"

namespace r4dx::server {

class ResponseSink {
 public:
  virtual ~ResponseSink() = default;

  // Called once, before the first generated token, with the full prompt token count (for the
  // response's `usage.prompt_tokens`).
  virtual void OnStart(int64_t prompt_tokens) = 0;

  // Called once per newly-decoded piece of text (Tokenizer::StreamDecoder::push's return value --
  // may span more or less than one token, see tokenizer.h).
  virtual void OnToken(const std::string& piece) = 0;

  // Called exactly once, after either the last OnToken or immediately (zero generated tokens).
  // `finish_reason` is one of "stop" (eos or a --stop string matched), "length" (max_tokens
  // reached), or "cancelled" (client disconnected mid-stream, see IsCancelled below). `timings`
  // (task's "timings" object, llama.cpp-compatible field names) is always attached as a top-level
  // sibling of `usage` in whatever this sink ultimately produces -- BufferingSink just stores it
  // for http_server.cpp to hand to the non-streaming response builders; StreamingSink attaches it
  // to the finish_reason chunk it pushes here. Defaulted so call sites that don't care (most
  // existing tests) don't need updating. `reasoning_tokens` (docs/server.md's "reasoning_content"
  // section, task item 5f) is the number of generated tokens up to and including the "</think>"
  // close tag -- meaningless (and left at its default 0) for a request that had thinking off,
  // computed by Engine::RunRequest (the only place that has both token boundaries and decoded text
  // at once) and handed through here rather than derived by the sink itself.
  virtual void OnDone(const std::string& finish_reason, int64_t completion_tokens,
                       const TimingStats& timings = {}, int64_t reasoning_tokens = 0) = 0;

  // Called instead of OnDone if something failed before or during generation (a bad request that
  // slipped past validation, a KV-cache-capacity overrun, ...).
  virtual void OnError(int http_status, const std::string& message) = 0;

  // Called at most once, strictly before OnDone, iff Engine parsed one or more structured tool
  // calls out of this generation (docs/server.md's "Tool calls" -- streaming decision: the CALLS
  // themselves are always buffered whole and delivered here as a single complete batch, never as
  // incremental per-argument-byte deltas the way OpenAI's own server streams them; the answer text
  // around them does stream live on a streaming request, see ToolStreamGate, tool_stream_gate.h).
  // Default no-op so ResponseSink's other implementations (were there any that don't care) don't
  // have to override it.
  virtual void OnToolCalls(const std::vector<ToolCallOut>& /*calls*/) {}

  // Called at most once, strictly before OnDone and OnToken, carrying the ALREADY-TRIMMED thinking
  // span this generation started with (docs/server.md's "reasoning_content" section, task item 5d)
  // -- the one-shot equivalent of OnToken's per-piece reasoning/content split, used ONLY by
  // Engine::RunRequest's NON-streaming tool-call path, which strips the thinking span out of the
  // accumulated text BEFORE tool-call parsing even runs (so it never flows through OnToken's
  // incremental splitter at all -- see ReasoningSplitter's own file comment). A STREAMING
  // tool-offering request does not use this: it forwards raw generated bytes to OnToken as they
  // arrive, exactly like a request with no tools, and the sink's own splitter produces live
  // per-piece reasoning_content deltas. Calling this marks the sink as "reasoning already
  // delivered", so a subsequent OnToken() call is treated as plain content with no further
  // tag-scanning (`parsed.content` by this point cannot contain the tag either, since it was
  // already stripped). Default no-op so a sink constructed with thinking off, or any caller that
  // never calls it, is unaffected.
  virtual void OnReasoningContent(const std::string& /*text*/) {}

  // The worker polls this between decode steps; true means stop generating now. Only
  // StreamingSink ever returns true (set by Cancel() when the HTTP layer detects the client is
  // gone); BufferingSink's non-streaming request has no analogous "give up early" signal.
  virtual bool IsCancelled() const { return false; }
};

// Non-streaming (/v1/chat/completions and /v1/completions with "stream" false or absent): buffers
// the whole reply, then wakes the HTTP handler thread blocked in Wait() once OnDone/OnError runs.
//
// `enable_thinking` (task item 5, defaulted to `false` so every existing `BufferingSink sink;` call
// site keeps compiling and behaving byte-for-byte identically -- task item 5c's own requirement):
// when true, OnToken's incoming pieces are routed through an internal ReasoningSplitter instead of
// being appended straight to `text` -- see that field's own doc comment for the resulting split.
//
// `emit_reasoning` (OpenRouter's `reasoning.exclude` / `include_reasoning: false`,
// ThinkingControls::include_reasoning): when false, the split still happens exactly as above (so
// `text` is still the ANSWER half alone) but `reasoning_text` is left empty and never returned.
// Only meaningful alongside `enable_thinking`; defaulted to true so every existing call site is
// unaffected.
class BufferingSink : public ResponseSink {
 public:
  explicit BufferingSink(bool enable_thinking = false, bool emit_reasoning = true)
      : enable_thinking_(enable_thinking), emit_reasoning_(emit_reasoning) {}

  void OnStart(int64_t prompt_tokens) override;
  void OnToken(const std::string& piece) override;
  void OnDone(const std::string& finish_reason, int64_t completion_tokens,
              const TimingStats& timings = {}, int64_t reasoning_tokens = 0) override;
  void OnError(int http_status, const std::string& message) override;

  // Blocks the calling thread until OnDone or OnError has been called.
  void Wait();

  void OnToolCalls(const std::vector<ToolCallOut>& calls) override;
  void OnReasoningContent(const std::string& text) override;

  // With `enable_thinking` false (the default), `text` behaves exactly as before this field
  // existed: every OnToken piece appended verbatim. With it true, `text` holds only the ANSWER
  // half of the split (task item 5a) and `reasoning_text` holds the trimmed reasoning half,
  // populated once OnDone runs (or immediately by OnReasoningContent in tool_mode, already trimmed
  // by the caller in that case -- see ResponseSink::OnReasoningContent's own doc comment).
  std::string text;
  std::string reasoning_text;
  int64_t reasoning_tokens = 0;  // set by OnDone; meaningless when `enable_thinking` is false
  std::string finish_reason;
  int64_t prompt_tokens = 0;
  int64_t completion_tokens = 0;
  TimingStats timings;  // set by OnDone -- http_server.cpp hands this to the response builders
  bool errored = false;
  int error_status = 500;
  std::string error_message;
  std::vector<ToolCallOut> tool_calls;  // set by OnToolCalls, empty for a plain-text response

 private:
  const bool enable_thinking_;
  const bool emit_reasoning_;
  ReasoningSplitter splitter_;
  std::string reasoning_raw_;      // un-trimmed accumulation of every kReasoning event
  bool reasoning_delivered_ = false;  // true once OnReasoningContent ran (tool_mode) -- OnToken
                                       // then bypasses the splitter entirely, see OnToken's body
  std::mutex mu_;
  std::condition_variable cv_;
  bool done_ = false;
};

// Streaming: formats each event as an OpenAI SSE chunk (chat.completion.chunk or text_completion,
// per `kind`) and hands the formatted "data: ...\n\n" string to httplib's chunked content
// provider (http_server.cpp) via a small blocking queue.
class StreamingSink : public ResponseSink {
 public:
  enum class Kind { kChat, kCompletion };

  // `include_usage`: this request's `stream_options.include_usage` (openai_types.h). When true,
  // every chunk this sink pushes carries a top-level `"usage": null` except one dedicated chunk
  // pushed after the finish_reason chunk (empty `choices`, the real `usage` + `timings`), right
  // before `[DONE]` -- OpenAI's own `stream_options.include_usage` contract.
  // `enable_thinking` (task item 5b, defaulted to `false` -- every existing call site keeps
  // compiling and behaving byte-for-byte identically, task item 5c): when true (and `kind ==
  // kChat` -- /v1/completions never splits, task item 5g), OnToken's incoming pieces are routed
  // through an internal ReasoningSplitter and pushed as `{"reasoning_content": ...}` deltas while
  // inside the thinking span, `{"content": ...}` deltas after it -- never both keys in one delta.
  // `emit_reasoning` (OpenRouter's `reasoning.exclude` / `include_reasoning: false`,
  // ThinkingControls::include_reasoning): when false, the split still runs identically but the
  // `reasoning_content` deltas are dropped instead of pushed -- the client sees only the answer's
  // `content` deltas. Only meaningful alongside `enable_thinking`; defaulted to true so every
  // existing call site is unaffected.
  StreamingSink(Kind kind, std::string id, std::string model_id, int64_t created_unix,
                bool include_usage = false, bool enable_thinking = false,
                bool emit_reasoning = true);

  void OnStart(int64_t prompt_tokens) override;
  void OnToken(const std::string& piece) override;
  void OnDone(const std::string& finish_reason, int64_t completion_tokens,
              const TimingStats& timings = {}, int64_t reasoning_tokens = 0) override;
  void OnError(int http_status, const std::string& message) override;
  void OnToolCalls(const std::vector<ToolCallOut>& calls) override;
  void OnReasoningContent(const std::string& text) override;
  bool IsCancelled() const override { return cancelled_.load(std::memory_order_relaxed); }

  // Called by the HTTP handler thread (httplib's chunked-content-provider callback) to pull the
  // next formatted SSE event; blocks until one is available. Returns false once the stream is
  // finished (queue closed and drained) -- the caller should stop calling and end the response.
  bool Next(std::string& out);

  // Called by the HTTP handler thread when the client disconnects (DataSink::write/is_writable
  // fails) -- makes IsCancelled() true so the worker's generation loop stops at its next check,
  // and unblocks any Next()/Push() waiter. Idempotent.
  void Cancel();

 private:
  // Pushes one `{"reasoning_content": text}` or `{"content": text}` delta chunk, per `is_reasoning`
  // -- the shared tail of OnToken's per-event loop and OnDone's Finish()-flush loop.
  void PushSplitDelta(bool is_reasoning, const std::string& text);

  Kind kind_;
  std::string id_, model_id_;
  int64_t created_unix_;
  bool include_usage_;
  bool enable_thinking_;
  bool emit_reasoning_;
  ReasoningSplitter splitter_;
  bool reasoning_delivered_ = false;  // true once OnReasoningContent ran (tool_mode) -- OnToken
                                       // then bypasses the splitter entirely, see OnToken's body
  int64_t prompt_tokens_ = 0;  // set by OnStart, used to build the dedicated usage chunk's usage
                                // object (OnDone only receives completion_tokens directly).
  std::atomic<bool> cancelled_{false};
  BoundedQueue<std::string> queue_;  // formatted SSE events; small bounded capacity gives natural
                                      // backpressure against a slow/stalled client.
};

}  // namespace r4dx::server
