// tests/kernels/test_rope_neox.cpp -- r4dx_rope_neox_bf16 (docs/dflash2.md "Kernels", section 3)
// against (1) a CPU fp32 reference at random absolute positions, (2) the Q-only / K-only calling
// forms the DFlash2 injection path needs, and (3) fixture A's own layer-0 pre-rope -> post-rope
// pair for both Q and K, which is generated by tools/reference/dflash2_ref.py's `rope_neox`.
//
// (3) is the anchor that matters: the pre-rope arrays (`attn_q_prerope_l0`/`attn_k_prerope_l0`)
// and the post-rope arrays (`attn_q_l0`/`attn_k_l0`) both come from the Python reference, so this
// check exercises the kernel against numbers no C++ code in this repo produced -- it would fail on
// a wrong pairing, a wrong theta, a wrong rotation sign, or a wrong per-row position, none of
// which the CPU-reference check in (1) can rule out on its own (that one only proves the kernel
// agrees with a second implementation of the same formula written here).
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <random>
#include <vector>

#include "npy_fixture.hpp"
#include "r4dx/core/device_buffer.hpp"
#include "r4dx/core/dtype.hpp"
#include "r4dx/core/error.hpp"
#include "r4dx/kernels/kernels.h"

using namespace r4dx::core;
using namespace r4dx_test;

namespace {

// docs/dflash2.md section 3, verbatim: half = head_dim/2, inv_freq[i] = theta^(-2i/head_dim),
// out[i] = x[i]*cos - x[i+half]*sin, out[i+half] = x[i+half]*cos + x[i]*sin. Computed the same way
// tests/kernels/test_rope.cpp's own reference is (float32 angle, double sin/cos) so this isolates
// the rotation, not the angle's inherent float32 quantisation -- see that file's comment.
void RopeNeoxRef(std::vector<uint16_t>* x, int rows, int heads, int head_dim, float theta,
                 const std::vector<int32_t>& pos_ids) {
  const int half = head_dim / 2;
  for (int t = 0; t < rows; ++t) {
    const float pos = static_cast<float>(pos_ids[t]);
    for (int hd = 0; hd < half; ++hd) {
      const float inv_freq =
          std::exp2(-(2.0f * hd) / static_cast<float>(head_dim) * std::log2(theta));
      const double angle = static_cast<double>(pos * inv_freq);
      const double c = std::cos(angle), s = std::sin(angle);
      for (int h = 0; h < heads; ++h) {
        const size_t base = (static_cast<size_t>(t) * heads + h) * head_dim;
        const double x0 = Bf16ToFloat((*x)[base + hd]);
        const double x1 = Bf16ToFloat((*x)[base + hd + half]);
        (*x)[base + hd] = FloatToBf16(static_cast<float>(x0 * c - x1 * s));
        (*x)[base + hd + half] = FloatToBf16(static_cast<float>(x1 * c + x0 * s));
      }
    }
  }
}

ErrStats CompareBf16(const std::vector<uint16_t>& got, const std::vector<uint16_t>& ref) {
  std::vector<float> reff(ref.size());
  for (size_t i = 0; i < ref.size(); ++i) reff[i] = Bf16ToFloat(ref[i]);
  return CompareToRef(got, reff);
}

}  // namespace

int main() {
  // Unbuffered: a GPU test that dies (a kernel fault, or an abort out of a failed HIP check)
  // takes the CRT's stdout buffer with it, and a crash report with zero output says nothing about
  // which check was running. Costs nothing at this output volume.
  std::setvbuf(stdout, nullptr, _IONBF, 0);
  R4DX_HIP_CHECK(hipSetDevice(0));
  bool ok = true;

  const int head_dim = 128;  // DFlash2: n_rot == head_dim, full-width rotation
  const float theta = 1.0e7f;
  std::mt19937 rng(7);
  std::uniform_real_distribution<float> dist(-3.0f, 3.0f);

  // ---- 1. CPU reference, two position regimes ----
  //
  // METRICS. The gate is `max_abs` plus the aggregate `norm_rel`, NOT `max_rel`. A rope is a
  // rotation: `out = x0*cos - x1*sin` preserves the pair's norm, so with inputs drawn from
  // [-3, 3] every output lies in [-3*sqrt(2), 3*sqrt(2)] and is then rounded to bf16, whose step
  // at that magnitude is 2^2 * 2^-8 = 3.125e-2. That quantum is the per-element error floor for
  // ANY correct implementation, and it is also why `max_rel` is meaningless here: the same
  // rotation drives some outputs to near zero by cancellation, where one last-place step against
  // a ~0 reference reads as max_rel ~ 1 while being the smallest possible disagreement. The
  // thresholds below (<= 2 bf16 steps, and a norm-relative bound 3 orders of magnitude under 1)
  // are still sharp: a wrong pairing, theta, rotation sign or per-row position produces an
  // essentially unrelated vector -- max_abs ~ |x| ~ 3 and norm_rel ~ 1, i.e. 100x and 1000x over.
  //
  // WHY TWO REGIMES. The kernel and this file's reference build `inv_freq` with the SAME fp32
  // expression, but `exp2f`/`log2f` are the device's (OCML) and `std::exp2`/`std::log2` are the
  // host's, and they may land one fp32 ulp apart (~1.2e-7 relative). The angle is
  // `pos * inv_freq`, so that one ulp is AMPLIFIED by `pos`: at pos ~ 3e5 it becomes ~0.036 rad of
  // angle disagreement, which moves cos/sin by ~0.036 and the output by ~|x| * 0.036. That is a
  // property of doing rope in fp32 at a huge position, not a kernel defect -- and it is exactly
  // what the two regimes make visible, since `norm_rel` is an order of magnitude smaller in the
  // first than in the second while `max_abs` stays pinned at the bf16 quantum in both.
  //   * `pos <= 4096` -- comfortably above any position this drafter's 2048-wide window ropes.
  //   * `pos <= 300000` -- past the target's full 262144 context.
  struct Regime {
    const char* label;
    int max_pos;
    double max_abs_tol;   // 2 bf16 steps at the output's magnitude range
    double norm_rel_tol;  // aggregate gate
  };
  for (const Regime& reg : {Regime{"pos <= 4096 (drafter window)", 4096, 6.3e-2, 1e-3},
                            Regime{"pos <= 300000 (full context)", 300000, 6.3e-2, 1e-3}}) {
    const int rows = 13, heads_q = 32, heads_k = 8;
    std::vector<uint16_t> q_h(static_cast<size_t>(rows) * heads_q * head_dim);
    std::vector<uint16_t> k_h(static_cast<size_t>(rows) * heads_k * head_dim);
    for (auto& v : q_h) v = FloatToBf16(dist(rng));
    for (auto& v : k_h) v = FloatToBf16(dist(rng));
    std::uniform_int_distribution<int> pdist(0, reg.max_pos);
    std::vector<int32_t> pos(rows);
    for (int t = 0; t < rows; ++t) pos[t] = pdist(rng);
    pos[0] = 0;  // position 0 must be the identity rotation

    std::vector<uint16_t> q_ref = q_h, k_ref = k_h;
    RopeNeoxRef(&q_ref, rows, heads_q, head_dim, theta, pos);
    RopeNeoxRef(&k_ref, rows, heads_k, head_dim, theta, pos);

    DeviceBuffer<uint16_t> q_d(q_h.size()), k_d(k_h.size());
    DeviceBuffer<int32_t> p_d(pos.size());
    q_d.CopyFromHost(q_h);
    k_d.CopyFromHost(k_h);
    p_d.CopyFromHost(pos);
    r4dx_rope_neox_bf16(reinterpret_cast<int64_t>(q_d.data()),
                         reinterpret_cast<int64_t>(k_d.data()),
                         reinterpret_cast<int64_t>(p_d.data()), rows, heads_q, heads_k, head_dim,
                         theta, 0);
    R4DX_HIP_CHECK(hipDeviceSynchronize());

    const std::vector<uint16_t> q_got = q_d.CopyToHost();
    const std::vector<uint16_t> k_got = k_d.CopyToHost();
    const ErrStats sq = CompareBf16(q_got, q_ref);
    const ErrStats sk = CompareBf16(k_got, k_ref);
    std::printf("[1] %-30s q norm_rel=%.3e max_abs=%.3e | k norm_rel=%.3e max_abs=%.3e\n",
                reg.label, sq.norm_rel, sq.max_abs, sk.norm_rel, sk.max_abs);
    const bool pass = sq.norm_rel < reg.norm_rel_tol && sk.norm_rel < reg.norm_rel_tol &&
                      sq.max_abs < reg.max_abs_tol && sk.max_abs < reg.max_abs_tol;
    std::printf("[1] %s\n", pass ? "PASS" : "FAIL");
    ok = ok && pass;

    // Row 0 (pos 0) must be bit-identical to the input: cos(0)=1, sin(0)=0.
    bool identity_ok = true;
    for (size_t i = 0; i < static_cast<size_t>(heads_q) * head_dim; ++i) {
      if (q_got[i] != q_h[i]) identity_ok = false;
    }
    std::printf("[1b] pos=0 is the bit-exact identity: %s\n", identity_ok ? "PASS" : "FAIL");
    ok = ok && identity_ok;
  }

  // ---- 2. Q-only / K-only calling forms (the DFlash2 injection path ropes K only) ----
  {
    const int rows = 5, heads_q = 32, heads_k = 8;
    std::vector<uint16_t> q_h(static_cast<size_t>(rows) * heads_q * head_dim);
    std::vector<uint16_t> k_h(static_cast<size_t>(rows) * heads_k * head_dim);
    for (auto& v : q_h) v = FloatToBf16(dist(rng));
    for (auto& v : k_h) v = FloatToBf16(dist(rng));
    std::vector<int32_t> pos(rows);
    for (int t = 0; t < rows; ++t) pos[t] = 1000 + 37 * t;

    DeviceBuffer<uint16_t> both_q(q_h.size()), both_k(k_h.size());
    DeviceBuffer<uint16_t> only_q(q_h.size()), only_k(k_h.size());
    DeviceBuffer<int32_t> p_d(pos.size());
    both_q.CopyFromHost(q_h);
    both_k.CopyFromHost(k_h);
    only_q.CopyFromHost(q_h);
    only_k.CopyFromHost(k_h);
    p_d.CopyFromHost(pos);

    r4dx_rope_neox_bf16(reinterpret_cast<int64_t>(both_q.data()),
                         reinterpret_cast<int64_t>(both_k.data()),
                         reinterpret_cast<int64_t>(p_d.data()), rows, heads_q, heads_k, head_dim,
                         theta, 0);
    // Q only: k pointer and head count both zero.
    r4dx_rope_neox_bf16(reinterpret_cast<int64_t>(only_q.data()), 0,
                         reinterpret_cast<int64_t>(p_d.data()), rows, heads_q, 0, head_dim, theta,
                         0);
    // K only: q pointer and head count both zero (the injection path).
    r4dx_rope_neox_bf16(0, reinterpret_cast<int64_t>(only_k.data()),
                         reinterpret_cast<int64_t>(p_d.data()), rows, 0, heads_k, head_dim, theta,
                         0);
    R4DX_HIP_CHECK(hipDeviceSynchronize());

    const bool q_same = both_q.CopyToHost() == only_q.CopyToHost();
    const bool k_same = both_k.CopyToHost() == only_k.CopyToHost();
    std::printf("[2] q-only matches combined: %s | k-only matches combined: %s\n",
                q_same ? "yes" : "no", k_same ? "yes" : "no");
    std::printf("[2] %s\n", (q_same && k_same) ? "PASS" : "FAIL");
    ok = ok && q_same && k_same;
  }

  // ---- 3. Fixture A: layer-0 pre-rope -> post-rope, both Q and K ----
  if (!FixtureAvailable()) {
    std::fprintf(stderr,
                 "[SKIP] fixture A not found at %s -- regenerate with\n"
                 "       <reference venv>/python.exe tools/reference/dflash2_ref.py "
                 "--gen-fixtures all --seed 0\n"
                 "       (gitignored + exactly reproducible, see docs/dflash2.md section 9)\n",
                 FixtureDir().c_str());
    return ok ? kSkipReturnCode : 1;
  }
  {
    const std::string d = FixtureDir();
    // n_injected == the block's start position; read it off the store's own row count rather than
    // hardcoding 40, so a fixture regenerated at a different N still drives this correctly.
    const int64_t n_injected = NpyShape(d + "/injected_k_l0.npy")[0];
    const std::vector<float> q_pre = LoadNpyF32(d + "/attn_q_prerope_l0.npy", {8, 32, 128});
    const std::vector<float> k_pre = LoadNpyF32(d + "/attn_k_prerope_l0.npy", {8, 8, 128});
    const std::vector<float> q_post = LoadNpyF32(d + "/attn_q_l0.npy", {8, 32, 128});
    const std::vector<float> k_post = LoadNpyF32(d + "/attn_k_l0.npy", {8, 8, 128});

    const int rows = 8;
    std::vector<int32_t> pos(rows);
    for (int t = 0; t < rows; ++t) pos[t] = static_cast<int32_t>(n_injected) + t;

    const std::vector<uint16_t> q_in = ToBf16(q_pre);
    const std::vector<uint16_t> k_in = ToBf16(k_pre);
    DeviceBuffer<uint16_t> q_d(q_in.size()), k_d(k_in.size());
    DeviceBuffer<int32_t> p_d(pos.size());
    q_d.CopyFromHost(q_in);
    k_d.CopyFromHost(k_in);
    p_d.CopyFromHost(pos);
    r4dx_rope_neox_bf16(reinterpret_cast<int64_t>(q_d.data()),
                         reinterpret_cast<int64_t>(k_d.data()),
                         reinterpret_cast<int64_t>(p_d.data()), rows, 32, 8, head_dim, theta, 0);
    R4DX_HIP_CHECK(hipDeviceSynchronize());

    const ErrStats sq = CompareToRef(q_d.CopyToHost(), q_post);
    const ErrStats sk = CompareToRef(k_d.CopyToHost(), k_post);
    // max_rel is deliberately not printed: see check [1]'s METRICS note (cancellation makes it
    // read ~1 for the smallest representable disagreement).
    std::printf("[3] fixture A (n_injected=%lld, pos %lld..%lld): q max_abs=%.3e norm_rel=%.3e | "
                "k max_abs=%.3e norm_rel=%.3e\n",
                (long long)n_injected, (long long)n_injected, (long long)n_injected + 7,
                sq.max_abs, sq.norm_rel, sk.max_abs, sk.norm_rel);
    // Tolerance: the fixture is fp32, the kernel is bf16 in AND out, so the inputs alone are
    // quantised at ~2^-8 relative. A pure rotation preserves magnitude, so the norm-relative
    // error is bounded by that input quantisation (~4e-3), not by anything the kernel does.
    const bool pass = sq.norm_rel < 8e-3 && sk.norm_rel < 8e-3;
    std::printf("[3] %s\n", pass ? "PASS" : "FAIL");
    ok = ok && pass;
  }

  std::printf(ok ? "PASS\n" : "FAIL\n");
  return ok ? 0 : 1;
}
