// r4dx_convert::GgufReader unit test (task A1 item 1): reads tests/convert/fixtures/tiny.gguf
// (generated by tools/convert_ref/make_tiny_gguf.py --out tiny.gguf, checked in -- regenerate with
// `python tools/convert_ref/make_tiny_gguf.py --out tests/convert/fixtures/tiny.gguf` if the
// fixture's own hardcoded values below ever change) and checks every metadata value type this
// reader supports (including arrays and strings) and every tensor dtype (F32/F16/BF16/Q8_0)
// against the exact values the generator wrote. CPU-only, no HIP.
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "r4dx_convert/gguf_reader.hpp"
#include "r4dx_convert/safetensors_reader.hpp"  // Utf8ToWide

namespace {

bool g_ok = true;

bool Check(const char* label, bool cond) {
  std::printf("%-40s %s\n", label, cond ? "OK" : "FAIL");
  if (!cond) g_ok = false;
  return cond;
}

bool NearlyEqual(float a, float b, float tol) { return std::fabs(a - b) <= tol; }

}  // namespace

int main() {
  using namespace r4dx_convert;

#ifndef R4DX_CONVERT_FIXTURES_DIR
#error "R4DX_CONVERT_FIXTURES_DIR must be defined by CMake"
#endif
  const std::string path = std::string(R4DX_CONVERT_FIXTURES_DIR) + "\\tiny.gguf";
  GgufReader r(Utf8ToWide(path));

  Check("version == 3", r.Version() == 3);
  Check("alignment == 32", r.Alignment() == 32);

  // ---- metadata: every scalar type ----
  Check("general.architecture", r.GetString("general.architecture") == "test");
  Check("u8", r.GetInt("test.u8") == 200);
  Check("i8", r.GetInt("test.i8") == -100);
  Check("u16", r.GetInt("test.u16") == 40000);
  Check("i16", r.GetInt("test.i16") == -30000);
  Check("u32", r.GetInt("test.u32") == 3000000000LL);
  Check("i32", r.GetInt("test.i32") == -2000000000LL);
  Check("u64", r.GetInt("test.u64") == 12345678901234LL);
  Check("i64", r.GetInt("test.i64") == -12345678901234LL);
  Check("f32", NearlyEqual(static_cast<float>(r.GetFloat("test.f32")), 3.5f, 1e-6f));
  Check("f64", NearlyEqual(static_cast<float>(r.GetFloat("test.f64")), -2.25f, 1e-9f));
  Check("bool_true", r.GetBool("test.bool_true") == true);
  Check("bool_false", r.GetBool("test.bool_false") == false);
  Check("string", r.GetString("test.str") == "hello gguf");

  // ---- metadata: arrays ----
  {
    auto v = r.GetIntArray("test.arr_i32");
    Check("arr_i32 size", v.size() == 5);
    Check("arr_i32 values", v == std::vector<int64_t>({1, 2, 3, 4, 5}));
  }
  {
    auto v = r.GetStringArray("test.arr_str");
    Check("arr_str size", v.size() == 3);
    Check("arr_str values", v[0] == "a" && v[1] == "bb" && v[2] == "ccc");
  }
  {
    auto v = r.GetBoolArray("test.arr_bool");
    Check("arr_bool size", v.size() == 3);
    Check("arr_bool values", v[0] == true && v[1] == false && v[2] == true);
  }
  Check("missing key throws", [&] {
    try {
      (void)r.GetInt("no.such.key");
      return false;
    } catch (const std::exception&) {
      return true;
    }
  }());

  // ---- tensors: directory ----
  Check("HasTensor t_f32", r.HasTensor("t_f32"));
  Check("HasTensor t_f16", r.HasTensor("t_f16"));
  Check("HasTensor t_bf16", r.HasTensor("t_bf16"));
  Check("HasTensor t_q8_0", r.HasTensor("t_q8_0"));
  Check("!HasTensor bogus", !r.HasTensor("does_not_exist"));
  Check("TensorNames count == 4", r.TensorNames().size() == 4);

  // ---- tensors: shapes (GGUF ne order, ne[0] fastest/innermost) ----
  Check("t_f32 ne", r.TensorInfo("t_f32").ne == std::vector<int64_t>({4, 3}));
  Check("t_f16 ne", r.TensorInfo("t_f16").ne == std::vector<int64_t>({5, 2}));
  Check("t_bf16 ne", r.TensorInfo("t_bf16").ne == std::vector<int64_t>({3, 2}));
  Check("t_q8_0 ne", r.TensorInfo("t_q8_0").ne == std::vector<int64_t>({64}));
  Check("t_f32 type", r.TensorInfo("t_f32").type == GgmlType::kF32);
  Check("t_f16 type", r.TensorInfo("t_f16").type == GgmlType::kF16);
  Check("t_bf16 type", r.TensorInfo("t_bf16").type == GgmlType::kBF16);
  Check("t_q8_0 type", r.TensorInfo("t_q8_0").type == GgmlType::kQ8_0);

  // ---- tensors: dequant vs. the generator's own known values ----
  {
    const std::vector<float> expected = {-6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5};
    auto got = r.DequantToF32("t_f32");
    Check("t_f32 elem count", got.size() == expected.size());
    bool ok = true;
    for (size_t i = 0; i < expected.size() && i < got.size(); ++i)
      ok &= NearlyEqual(got[i], expected[i], 1e-6f);
    Check("t_f32 values exact", ok);
  }
  {
    const std::vector<float> expected = {-2.5f, -2, -1.5f, -1, -0.5f, 0, 0.5f, 1, 1.5f, 2};
    auto got = r.DequantToF32("t_f16");
    bool ok = got.size() == expected.size();
    for (size_t i = 0; i < expected.size() && i < got.size(); ++i)
      ok &= NearlyEqual(got[i], expected[i], 1e-3f);
    Check("t_f16 values exact (f16 round-trip)", ok);
  }
  {
    const std::vector<float> expected = {-6, -4, -2, 0, 2, 4};
    auto got = r.DequantToF32("t_bf16");
    bool ok = got.size() == expected.size();
    for (size_t i = 0; i < expected.size() && i < got.size(); ++i)
      ok &= NearlyEqual(got[i], expected[i], 1e-3f);
    Check("t_bf16 values exact (every value bf16-representable)", ok);
  }
  {
    // Q8_0: 2 blocks of 32, values -16..15 then -32,-30,..,30 -- lossy (int8 quant), so only a
    // loose tolerance is asserted (rung 1's "packer byte-exact" contract is about DETERMINISM,
    // not accuracy -- this is the reader's decode path, which is the analogous rung for a
    // container the loader will read, so a coarse sanity bound is the right gate here).
    std::vector<float> expected;
    for (int i = 0; i < 32; ++i) expected.push_back(static_cast<float>(i - 16));
    for (int i = 0; i < 32; ++i) expected.push_back(static_cast<float>(2 * (i - 16)));
    auto got = r.DequantToF32("t_q8_0");
    bool ok = got.size() == expected.size();
    float max_abs_err = 0.0f;
    for (size_t i = 0; i < expected.size() && i < got.size(); ++i)
      max_abs_err = std::max(max_abs_err, std::fabs(got[i] - expected[i]));
    ok &= (max_abs_err < 0.15f);
    Check("t_q8_0 values within Q8_0 tolerance", ok);
    std::printf("t_q8_0 max_abs_err=%.6f\n", max_abs_err);
  }
  {
    // Free-standing static decoder, exercised the same way a caller with no GgufReader instance
    // (e.g. a future fixed-layout consumer) would use it.
    std::vector<uint8_t> raw(r.TensorInfo("t_q8_0").nbytes);
    std::memcpy(raw.data(), r.TensorData("t_q8_0"), raw.size());
    std::vector<float> out(64);
    GgufReader::DequantQ8_0ToF32(raw.data(), 64, out.data());
    Check("static DequantQ8_0ToF32 matches instance method",
          NearlyEqual(out[0], r.DequantToF32("t_q8_0")[0], 1e-6f));
  }
  {
    auto bf16 = r.DequantToBf16("t_f32");
    Check("DequantToBf16 size", bf16.size() == 12);
    Check("DequantToBf16 round-trips exactly (integers are bf16-exact)",
          r4dx::core::Bf16ToFloat(bf16[0]) == -6.0f);
  }

  if (!g_ok) return 1;
  std::printf("PASS\n");
  return 0;
}
