// DFlash2 draft container tests (task A1 item 6): metadata + tensor directory round-trip on the
// 2-layer/64-dim/512-vocab miniature GGUF (tests/convert/fixtures/dflash_mini.gguf, generated by
// `python tools/convert_ref/make_tiny_gguf.py --dflash-mini --out
// tests/convert/fixtures/dflash_mini.gguf`), plus the linear-weight orientation test (task A1's
// "get it right, with a test"). CPU-only, no HIP -- builds a real container via the same
// Plan*/Emit* helpers src/convert/main.cpp's --dflash-gguf mode uses, then reads it back with
// r4dx_convert::SafetensorsReader (the container shell IS safetensors-shaped, same reader
// src/model/container.cpp uses).
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <string>
#include <vector>

#include "nlohmann/json.hpp"
#include "r4dx/core/dtype.hpp"
#include "r4dx_convert/container_writer.hpp"
#include "r4dx_convert/dflash2_container.hpp"
#include "r4dx_convert/gguf_reader.hpp"
#include "r4dx_convert/safetensors_reader.hpp"

namespace {

bool g_ok = true;
bool Check(const char* label, bool cond) {
  std::printf("%-56s %s\n", label, cond ? "OK" : "FAIL");
  if (!cond) g_ok = false;
  return cond;
}

nlohmann::json ReadContainerMetadata(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  uint64_t header_len = 0;
  f.read(reinterpret_cast<char*>(&header_len), 8);
  std::string header_json(static_cast<size_t>(header_len), '\0');
  f.read(header_json.data(), static_cast<std::streamsize>(header_len));
  return nlohmann::json::parse(header_json).at("__metadata__");
}

}  // namespace

int main() {
  using namespace r4dx_convert;

#ifndef R4DX_CONVERT_FIXTURES_DIR
#error "R4DX_CONVERT_FIXTURES_DIR must be defined by CMake"
#endif
  const std::string gguf_path = std::string(R4DX_CONVERT_FIXTURES_DIR) + "\\dflash_mini.gguf";
  GgufReader gguf(Utf8ToWide(gguf_path));

  // ---- metadata extraction ----
  Dflash2Metadata meta = ReadDflash2Metadata(gguf);
  Check("hidden", meta.hidden == 64);
  Check("block_count", meta.block_count == 2);
  Check("ffn", meta.ffn == 128);
  Check("head_count", meta.head_count == 4);
  Check("head_count_kv", meta.head_count_kv == 2);
  Check("key_length", meta.key_length == 16);
  Check("value_length", meta.value_length == 16);
  Check("causal == false", meta.causal == false);
  Check("sliding_window", meta.sliding_window == 64);
  Check("sliding_window_pattern size", meta.sliding_window_pattern.size() == 2);
  Check("conv_kernel_size", meta.conv_kernel_size == 2);
  Check("conv_group_size", meta.conv_group_size == 4);
  Check("selector_rank", meta.selector_rank == 32);
  Check("selector_top_k", meta.selector_top_k == 4);
  Check("block_size", meta.block_size == 8);
  Check("target_layers", meta.target_layers == std::vector<int64_t>({1, 2}));
  Check("mask_token_id", meta.mask_token_id == 500);
  // No dflash.rope.dimension_count key in the fixture (mirrors the real GGUF) -> n_rot defaults
  // to key_length, exactly the real-file behavior this converter must reproduce.
  Check("n_rot defaults to key_length", meta.n_rot == meta.key_length);
  // vocab_size is derived from selector_predecessor.weight's own shape, not a scalar KV key.
  Check("vocab_size derived from selector_predecessor shape", meta.vocab_size == 512);

  // ---- build a real (mini) container through the same helpers main.cpp's --dflash-gguf uses ----
  LayoutSet layouts;
  layouts.bf16 = true;
  layouts.w4a16 = true;  // exercise one quantized layout too (K=64 divisible by 128? NO -- see below)
  // kInt4Group is 128; this mini's K's (64, 128) -- 64 is NOT divisible by 128, so w4a16 would
  // fail PlanLinearLayouts's RequireDivisible for the K=64 linears (q_proj/conv_proj/etc). The
  // real model's every quantizable K (5120/17408/25600/1280) is a multiple of 128; this mini
  // fixture's whole point is to be small, which conflicts with that constraint for a genuine
  // 4-bit-layout round trip. bf16-only is therefore what this container-shape/orientation test
  // exercises for the GEMM-style linears; w4a16/w4a8/mxfp4 packers themselves already have their
  // own dedicated byte-exactness coverage (test_pack_bytes.cpp, test_kernel_decode.cpp) against
  // real-sized fixtures, so re-deriving that here would duplicate coverage rather than add any.
  layouts.w4a16 = false;

  const std::string out_path = std::string(std::getenv("TEMP") ? std::getenv("TEMP") : ".") +
                                "\\r4dx_test_dflash_container.r4dx";
  {
    ContainerWriter writer;
    PlanDflash2Linear(writer, gguf, {"blk.0.attn_q.weight", "dflash.layers.0.self_attn.q_proj"}, layouts);
    PlanDflash2Linear(writer, gguf, {"fc.weight", "dflash.fc"}, layouts);
    PlanDflash2Bf16(writer, gguf, "blk.0.attn_conv_base", "dflash.layers.0.self_attn.conv.base");
    PlanDflash2Bf16(writer, gguf, "selector_predecessor.weight", "dflash.selector.predecessor");
    PlanDflash2F32(writer, gguf, "blk.0.attn_norm.weight", "dflash.layers.0.input_layernorm");

    nlohmann::json metadata;
    metadata["r4dx_format_version"] = "1";
    metadata["container_kind"] = "dflash2_draft";
    metadata["dflash2"] = BuildDflash2MetadataJson(meta);
    writer.FinalizeHeader(out_path, metadata);

    EmitDflash2Linear(writer, gguf, {"blk.0.attn_q.weight", "dflash.layers.0.self_attn.q_proj"}, layouts, 1);
    EmitDflash2Linear(writer, gguf, {"fc.weight", "dflash.fc"}, layouts, 1);
    EmitDflash2Bf16(writer, gguf, "blk.0.attn_conv_base", "dflash.layers.0.self_attn.conv.base");
    EmitDflash2Bf16(writer, gguf, "selector_predecessor.weight", "dflash.selector.predecessor");
    EmitDflash2F32(writer, gguf, "blk.0.attn_norm.weight", "dflash.layers.0.input_layernorm");
    writer.Finish();
  }

  // ---- metadata round-trip ----
  {
    nlohmann::json md = ReadContainerMetadata(out_path);
    Check("container_kind", md.at("container_kind").get<std::string>() == "dflash2_draft");
    Check("dflash2.hidden_size round-trip", md.at("dflash2").at("hidden_size").get<int64_t>() == 64);
    Check("dflash2.target_layers round-trip",
          md.at("dflash2").at("target_layers").get<std::vector<int64_t>>() ==
              std::vector<int64_t>({1, 2}));
    Check("dflash2.rope.n_rot round-trip", md.at("dflash2").at("rope").at("n_rot").get<int64_t>() == 16);
  }

  // ---- tensor directory + orientation test ----
  SafetensorsReader r(Utf8ToWide(out_path));
  Check("has q_proj.bf16.w", r.Has("dflash.layers.0.self_attn.q_proj.bf16.w"));
  Check("has fc.bf16.w", r.Has("dflash.fc.bf16.w"));
  Check("has conv.base", r.Has("dflash.layers.0.self_attn.conv.base"));
  Check("has selector.predecessor", r.Has("dflash.selector.predecessor"));
  Check("has input_layernorm", r.Has("dflash.layers.0.input_layernorm"));

  {
    // Orientation (task A1's explicit "get it right, with a test"): the container's q_proj bf16
    // weight must be row-major [N=64,K=64] with row = OUTPUT feature, matching GGUF's own ne=
    // [64,64] (K=ne[0]=64 in, N=ne[1]=64 out) flattened order -- i.e. bit-identical to GGUF's own
    // DequantToBf16 of the same tensor, no transpose.
    auto expected = gguf.DequantToBf16("blk.0.attn_q.weight");
    const auto& m = r.Meta("dflash.layers.0.self_attn.q_proj.bf16.w");
    Check("q_proj container shape [N,K,2]", m.shape == std::vector<int64_t>({64, 64, 2}));
    const uint16_t* got = reinterpret_cast<const uint16_t*>(r.Data("dflash.layers.0.self_attn.q_proj.bf16.w"));
    bool bit_exact = true;
    for (size_t i = 0; i < expected.size(); ++i) bit_exact &= (got[i] == expected[i]);
    Check("q_proj orientation: bit-exact vs GGUF DequantToBf16 (no transpose)", bit_exact);
  }
  {
    auto expected = gguf.DequantToBf16("selector_predecessor.weight");
    const uint16_t* got = reinterpret_cast<const uint16_t*>(r.Data("dflash.selector.predecessor"));
    bool bit_exact = true;
    for (size_t i = 0; i < expected.size(); ++i) bit_exact &= (got[i] == expected[i]);
    Check("selector.predecessor row-gather bytes bit-exact (order preserved)", bit_exact);
    // GGUF ne=[selector_rank=32, vocab=512] (rank fastest) -> row-major declared shape is
    // [vocab, selector_rank, 2], the REVERSE of ne, not ne itself.
    const auto& m = r.Meta("dflash.selector.predecessor");
    Check("selector.predecessor shape [vocab,rank,2]", m.shape == std::vector<int64_t>({512, 32, 2}));
  }
  {
    auto expected = gguf.DequantToBf16("blk.0.attn_conv_base");
    const uint16_t* got = reinterpret_cast<const uint16_t*>(r.Data("dflash.layers.0.self_attn.conv.base"));
    bool bit_exact = true;
    for (size_t i = 0; i < expected.size(); ++i) bit_exact &= (got[i] == expected[i]);
    Check("conv.base [side][tap][h] order preserved, bit-exact", bit_exact);
    // GGUF ne=[hidden=64,2,2] (hidden fastest, bytes are [side][tap][hidden]) -> row-major
    // declared shape is [2 sides, 2 taps, hidden, 2], the REVERSE of ne, not ne itself.
    const auto& m = r.Meta("dflash.layers.0.self_attn.conv.base");
    Check("conv.base shape [sides,taps,hidden,2]", m.shape == std::vector<int64_t>({2, 2, 64, 2}));
  }
  {
    const auto& m = r.Meta("dflash.layers.0.input_layernorm");
    Check("norm stored f32 (trailing 4-byte axis)", m.shape == std::vector<int64_t>({64, 4}));
    Check("norm byte span == 64*4", (m.end - m.begin) == 64 * 4);
  }

  std::remove(out_path.c_str());
  if (!g_ok) return 1;
  std::printf("PASS\n");
  return 0;
}
