// Byte-exactness of the packer against fixtures generated by the Python references (task item 5
// / item 3's self-test): tests/convert/fixtures/input.safetensors holds one small bf16 weight;
// gen_fixtures.py quantized and packed it with tools/convert_ref/{w4_ref,mxfp4_ref}.py and saved
// every layout's bytes. This test re-derives the same bytes in C++ from the same input and
// memcmp's them -- any mismatch means the C++ packer and the Python ground truth have diverged.
//
// R4DX_CONVERT_FIXTURES_DIR is injected by tests/convert/CMakeLists.txt as an absolute path, so
// this runs correctly regardless of ctest's working directory.
#include <cstdio>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "nlohmann/json.hpp"
#include "r4dx_convert/quant_int4.hpp"
#include "r4dx_convert/quant_mxfp4.hpp"
#include "r4dx_convert/safetensors_reader.hpp"
#include "r4dx_convert/tensor_codec.hpp"

namespace {

std::vector<uint8_t> ReadFileBytes(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  if (!f) throw std::runtime_error("cannot open fixture: " + path);
  f.seekg(0, std::ios::end);
  size_t n = static_cast<size_t>(f.tellg());
  f.seekg(0);
  std::vector<uint8_t> buf(n);
  f.read(reinterpret_cast<char*>(buf.data()), static_cast<std::streamsize>(n));
  return buf;
}

template <typename T>
std::vector<uint8_t> AsBytes(const std::vector<T>& v) {
  const uint8_t* p = reinterpret_cast<const uint8_t*>(v.data());
  return std::vector<uint8_t>(p, p + v.size() * sizeof(T));
}

bool CompareBytes(const std::string& label, const std::vector<uint8_t>& got,
                  const std::vector<uint8_t>& want) {
  if (got.size() != want.size()) {
    std::fprintf(stderr, "FAIL %s: size mismatch got=%zu want=%zu\n", label.c_str(), got.size(),
                 want.size());
    return false;
  }
  for (size_t i = 0; i < got.size(); ++i) {
    if (got[i] != want[i]) {
      std::fprintf(stderr, "FAIL %s: first mismatch at byte %zu: got=0x%02x want=0x%02x\n",
                   label.c_str(), i, got[i], want[i]);
      return false;
    }
  }
  std::printf("OK   %s (%zu bytes byte-exact)\n", label.c_str(), got.size());
  return true;
}

// Fixture filename suffix for an int4 group: the historical 128 set keeps its unsuffixed names
// (its bytes are the ground truth every earlier milestone was gated against and must not move),
// every other group gets "_g{group}" -- tools/convert_ref/gen_fixtures.py's `gsfx`.
std::string GroupSuffix(int group) {
  return group == 128 ? std::string() : "_g" + std::to_string(group);
}

}  // namespace

int main() {
  using namespace r4dx_convert;
  const std::string dir = R4DX_CONVERT_FIXTURES_DIR;

  nlohmann::json manifest;
  {
    std::ifstream f(dir + "/manifest.json");
    f >> manifest;
  }
  const int N = manifest.at("N").get<int>();
  const int K = manifest.at("K").get<int>();

  SafetensorsReader reader(Utf8ToWide(dir + "/input.safetensors"));
  const uint16_t* src = reinterpret_cast<const uint16_t*>(reader.Data("w"));
  std::vector<float> w(static_cast<size_t>(N) * K);
  for (size_t i = 0; i < w.size(); ++i) w[i] = r4dx::core::Bf16ToFloat(src[i]);

  bool ok = true;

  // Every int4 group r4d_gemm_w4a16_nt_m64 can be built with (manifest.json's "int4_groups", from
  // gen_fixtures.py). Gating both here rather than only at kW4A16Group means the DEFAULT build
  // still proves the group-64 packer byte-exact against the Python reference.
  for (const auto& gj : manifest.at("int4_groups")) {
    const int group = gj.get<int>();
    const std::string g = GroupSuffix(group), tag = " g" + std::to_string(group);
    {
      std::vector<uint8_t> q, zero;
      std::vector<float> scale;
      QuantizeInt4Asymmetric(w.data(), N, K, group, /*nthreads=*/1, q, scale, zero);
      auto wq = PackW4Nibbles(q, N, K, /*nthreads=*/1);
      auto wsz = PackW4A16Scales(scale, zero, N, K, group);
      ok &= CompareBytes("w4a16.wq" + tag, AsBytes(wq),
                         ReadFileBytes(dir + "/w4a16_wq" + g + ".bin"));
      ok &= CompareBytes("w4a16.wsz" + tag, AsBytes(wsz),
                         ReadFileBytes(dir + "/w4a16_wsz" + g + ".bin"));
    }
    {
      std::vector<uint8_t> q;
      std::vector<float> scale;
      QuantizeInt4SymmetricPinned8(w.data(), N, K, group, /*nthreads=*/1, q, scale);
      auto wq = PackW4Nibbles(q, N, K, /*nthreads=*/1);
      auto ws = PackW4A8Scales(scale, N, K, group);
      ok &= CompareBytes("w4a8.wq" + tag, AsBytes(wq),
                         ReadFileBytes(dir + "/w4a8_wq" + g + ".bin"));
      ok &= CompareBytes("w4a8.ws" + tag, AsBytes(ws),
                         ReadFileBytes(dir + "/w4a8_ws" + g + ".bin"));
    }
  }
  {  // mxfp4's group is its own constant, not the w4a16 build option -- one set of fixtures.
    Mxfp4Quantized mq = QuantizeMxfp4(w.data(), N, K, kMxfp4Group, /*nthreads=*/1);
    auto wq = PackMxfp4Wq(mq.packed, N, K, /*nthreads=*/1);
    auto ws = PackMxfp4Ws(mq.escale, N, K, kMxfp4Group);
    ok &= CompareBytes("mxfp4.wq", wq, ReadFileBytes(dir + "/mxfp4_wq.bin"));
    ok &= CompareBytes("mxfp4.ws", ws, ReadFileBytes(dir + "/mxfp4_ws.bin"));
    ok &= CompareBytes("mxfp4.wref", mq.wref, ReadFileBytes(dir + "/mxfp4_wref.bin"));
  }

  if (!ok) return 1;
  std::printf("PASS\n");
  return 0;
}
