// r4dx::core::Arena: a bump allocator over one DeviceBuffer<uint8_t>, for per-step activation
// scratch (rmsnorm output, gate_up, attention scratch, ...) that is entirely re-derivable from
// the current token/layer and so never needs individual frees -- only Reset() between steps.
#pragma once

#include <cstddef>
#include <cstdint>
#include <new>
#include <stdexcept>

#include "r4dx/core/device_buffer.hpp"
#include "r4dx/core/error.hpp"

namespace r4dx::core {

class Arena {
 public:
  Arena() = default;
  explicit Arena(size_t capacity_bytes) : storage_(capacity_bytes) {}

  void Reserve(size_t capacity_bytes) {
    storage_.Resize(capacity_bytes);
    offset_ = 0;
  }

  // Bump-allocates `count` T's, aligned to alignof(T) (or `align_bytes` if given). Never frees
  // individually; call Reset() to reclaim everything at once. Throws std::bad_alloc if the arena
  // is exhausted -- a caller that hits this should Reserve() a bigger arena, not catch and retry.
  template <typename T>
  T* Alloc(size_t count, size_t align_bytes = alignof(T)) {
    if (align_bytes == 0 || (align_bytes & (align_bytes - 1)) != 0) {
      throw std::invalid_argument("Arena::Alloc: align_bytes must be a nonzero power of two");
    }
    // Overflow-check every step in size_t arithmetic before it can wrap: a huge `count` (e.g. a
    // corrupt shape) must throw std::bad_alloc, not silently wrap into a tiny in-bounds `bytes`
    // that then passes the base+bytes > capacity check and hands back a bogus pointer.
    size_t base = AlignUp(offset_, align_bytes);
    if (base < offset_) throw std::bad_alloc();  // AlignUp overflowed
    size_t bytes;
    if (__builtin_mul_overflow(count, sizeof(T), &bytes)) throw std::bad_alloc();
    size_t end;
    if (__builtin_add_overflow(base, bytes, &end)) throw std::bad_alloc();
    if (end > storage_.bytes()) {
      throw std::bad_alloc();
    }
    // Milestone 4 root-cause fix (docs/r9700.md R2/P2 correctness incident, 2026-09-20 follow-up):
    // `end` above is only as aligned as this ONE call's own (base + bytes) happens to land -- it is
    // NOT rounded to any particular boundary. Every third_party/libr4d kernel this arena feeds (the
    // GDN conv/kkt/chunk-scan family, every quantized GEMM's A-operand read, attention's decode
    // scratch) reads its device buffers with unchecked wide (16-byte) vector loads and never
    // verifies alignment itself -- unlike this project's own P6-rewritten rmsnorm/residual_rmsnorm/
    // silu_mul kernels, which fall back to a scalar loop when a buffer isn't 16-aligned. Before the
    // R2/P2 fusion pass, every Alloc call in every real call site happened to request a size that is
    // itself a multiple of 16 bytes (hidden=5120/conv_dim=10240/intermediate=17408 are all multiples
    // of 8 bf16 elements = 16 bytes), so `end` was always incidentally already 16-aligned and this
    // was never observable -- several call sites' own comments (gdn_layer.cpp, attention_layer.hpp,
    // linear.cpp) already flagged that invariant as "incidental, not enforced" before this fix.
    // R2/P2 broke the invariant: `next_epilogue_scale`/`x_normed_pre_scale`'s per-row fp32 scale
    // scratch is exactly `T` floats (T = a chunk's row count, 1..64 -- decode T=1, MTP verify
    // T=2..4, prefill chunks up to 64), so its byte count (4*T) is a multiple of 16 only when T is a
    // multiple of 4. At every other T, the NEXT default-aligned Alloc call in the same layer (e.g.
    // GdnLayer::Forward's `mixed_qkv`, alignof(uint16_t)=2) starts a few bytes short of a 16-byte
    // boundary, and every allocation AFTER that inherits the same drift for the rest of the layer's
    // scratch sequence -- until Reset(). A downstream libr4d kernel reading one of those drifted
    // buffers with an unchecked wide load then silently reads the wrong bytes rather than faulting,
    // which is exactly the "same generated bytes in isolation, different generated text end-to-end"
    // symptom docs/status.md's original R2/P2 incident reported (confirmed by bisection: forcing
    // every epilogue KERNEL to a no-op while keeping the SAME extra arena allocations still
    // reproduced the real-hardware divergence, isolating it to the allocation shift itself, not any
    // epilogue kernel's math -- tests/kernels/test_fused_quant.cpp's new ArenaAlignmentInvariant
    // check below reproduces the same shift directly, host-side, without needing a GPU divergence to
    // notice it).
    //
    // Fix: round `end` itself up to a 16-byte boundary before storing it as the next call's
    // `offset_`, so every FUTURE Alloc call -- regardless of what alignment IT individually
    // requests -- is guaranteed to start 16-aligned again, restoring the invariant the rest of this
    // codebase already silently depended on. At most 15 bytes of padding per call; negligible
    // against this arena's ~96 MiB reservation (model.cpp's Model::Load).
    constexpr size_t kMinAlign = 16;
    const size_t padded_end = AlignUp(end, kMinAlign);
    offset_ = (padded_end >= end && padded_end <= storage_.bytes()) ? padded_end : end;
    return reinterpret_cast<T*>(storage_.data() + base);
  }

  void Reset() noexcept { offset_ = 0; }

  size_t used_bytes() const noexcept { return offset_; }
  size_t capacity_bytes() const noexcept { return storage_.bytes(); }

 private:
  static size_t AlignUp(size_t v, size_t align) { return (v + align - 1) & ~(align - 1); }

  DeviceBuffer<uint8_t> storage_;
  size_t offset_ = 0;
};

}  // namespace r4dx::core
