#requires -Version 5.1
<#
.SYNOPSIS
  Mandatory end-to-end losslessness gate for DFlash2 self-speculative decode (docs/dflash2.md,
  Milestone 5 stage S3 item 4): proves `--dflash <container>` produces BYTE-IDENTICAL generated
  text to plain `--mtp 0` decode, by SHA-256 of the raw generated bytes -- not a tolerance-bounded
  diff. Modeled directly on tools/validate_fusion.ps1 (same exit-code/non-empty-stdout/pinned
  --max-ctx handling, same reason for each -- see that script's own comments for the review
  findings that shaped this contract).

.DESCRIPTION
  DFlash2's own correctness argument (docs/dflash2.md section 5) is that VerifyWindow always runs
  the REAL model over every candidate and only ever commits the prefix the real model's own greedy
  argmax confirms -- a drafted token that would have changed the output is, by construction, never
  accepted. This script is the repeatable, real-hardware regression gate for that argument: for
  every (target layout, prompt length) combination, runs r4dx-cli.exe against the same real target
  container -- `--mtp 0` (no speculation at all, the ground truth), `-Dflash <draft container>`
  (today only the w4a16 draft container, matching the task's own ask), and, ONLY when those two
  mismatch, a third CONTROL run `--mtp 7` (the existing, already-shipped MTP path, zero DFlash2 code
  involved at all) -- and compares SHA-256 of each pair's raw stdout.

  KNOWN, DOCUMENTED PRECEDENT for a non-match that is NOT a bug (docs/mtp.md): mxfp4's `--mtp 3`
  was already known to diverge from `--mtp 0` on the standard prompt because batched multi-row
  verification changes GEMM reduction order relative to sequential single-row decode, which is not
  bit-associative for floating point. THIS SCRIPT'S OWN FIRST RUN (2026-09-20) additionally found
  that w4a16 -- previously believed exempt (docs/mtp.md's own bf16-exact-arithmetic-style
  assumption, never actually tested at this prompt length before) -- shows the SAME mechanism on
  the ~250-token "medium" prompt: `r4dx-cli --mtp 3` (NO --dflash at all) was independently
  confirmed to diverge from `--mtp 0` with the EXACT SAME SHA-256 `--dflash` itself produced on
  that prompt (`build\logs\s3_debug_mtp_control.txt`) -- i.e. DFlash2's own divergence there is
  BYTE-IDENTICAL to plain MTP's, proving it is the pre-existing batched-verify mechanism, not
  anything DFlash2-specific, on real hardware, not by assumption. `--dflash` verifies through the
  exact same Model::VerifyWindow batched path MTP's own `--mtp N` does (both go through the SAME
  generalized VerifyWindow -- docs/dflash2.md section 7 item 3), so this mechanism applies
  identically to both, on every layout, not just mxfp4 -- this script's control run below makes
  that comparison directly, automatically, for every mismatch, rather than assuming it from a
  layout name.

  This script does NOT treat a divergence as an automatic pass: on any `--mtp 0` vs `--dflash`
  mismatch it (a) prints a character-level diff position and both texts' prefixes so a human can
  see whether the difference is "one token flips to a different-but-coherent continuation" (the
  batched-reduction-order signature) or "tokens dropped/duplicated/garbage" (a real bookkeeping
  bug), and (b) runs the `--mtp 7` control and reports whether IT ALSO diverges from `--mtp 0` on
  the identical prompt/layout -- if the control does NOT diverge, that is strong evidence the
  `--dflash` divergence is a REAL bug (dflash-specific), and the row is FAILED outright, no
  override available. Only when the control diverges too is the row downgraded to WARN (still
  requires -AllowBatchedVerifyDivergence -- a human decision, not a default).

.PARAMETER Model
  Path to the real 64-layer target container. Default: the production container matching build\win-hip's w4a16 group,
  read from build\win-hip\CMakeCache.txt (R4DX_W4A16_GROUP) by tools\r4dx_containers.ps1: group 64
  (the default build) -> D:\models\r4dx\qwen38-27b-v6.r4dx, group 128 -> D:\models\r4dx\qwen38-27b-v3.r4dx.

.PARAMETER Dflash
  Path to the DFlash2 draft container to test. Default: the w4a16 draft container matching the same group -- group 64 ->
  D:\models\r4dx\qwen38-27b-dflash2-w4a16-g64.r4dx, group 128 -> D:\models\r4dx\qwen38-27b-dflash2-w4a16.r4dx.
  (w4a16 is the task's own primary ask -- item 4 says "w4a16 draft" explicitly.)

.PARAMETER Layouts
  Comma-separated TARGET body layouts. Default: w4a16,w4a8,mxfp4 (bf16 excluded, standing
  bf16-retired-from-perf-work rule -- docs/status.md).

.PARAMETER MaxTokens
  --max-tokens for every generation. Default 40, matching validate_fusion.ps1's own default (long
  enough to exercise several DraftRound/verify rounds without making the full matrix slow).

.PARAMETER AllowBatchedVerifyDivergence
  If set, a `--mtp 0` vs `--dflash` mismatch is downgraded from FAILED to WARN (still printed, still
  shown in the summary table) IF AND ONLY IF this script's own `--mtp 7` control run against the
  SAME prompt/layout ALSO diverges from `--mtp 0` -- i.e. the mismatch is reproduced by the
  pre-existing, DFlash2-uninvolved MTP path, not just asserted to be that mechanism from a layout
  name. A mismatch whose control does NOT diverge is a hard FAILED regardless of this switch (that
  pattern would mean the divergence is dflash-specific, i.e. a real bug).

.PARAMETER Tp
  Tensor parallelism (docs/tp.md P5, gate G12): 1 (default) runs everything on HIP device 1, exactly
  as before this parameter existed. 2 passes `--tp 2` (real mode, both GPUs) to EVERY r4dx-cli run --
  ground truth, --dflash, and both controls alike, so every comparison is TP=2 against TP=2 -- and
  REMOVES HIP_VISIBLE_DEVICES and R4DX_TP_FAULT for the run (both restored at the end, from a
  finally: an error or Ctrl-C restores them too). It refuses to start while an r4dx-server is running
  (docs/tp.md 9.2); after every run it scans that run's stderr for HIP error 719 and, 5 s later, checks
  for a device-0 TDR (tools\tp\tdr_check.ps1, Appendix B N55), stopping at the first one (no retry);
  and on every exit it runs the check once more 30 s after the last run. A TDR fails the script (exit
  1). An MTP / DFlash2 mismatch here is classified by the script's own controls at --tp 2; running the
  same matrix at -Tp 1 on the same tree says whether it is also there at TP=1 (Appendix B N29, N80).

.EXAMPLE
  .\tools\validate_dflash.ps1
.EXAMPLE
  .\tools\validate_dflash.ps1 -Layouts w4a16 -MaxTokens 64
.EXAMPLE
  .\tools\validate_dflash.ps1 -Tp 2 -Layouts w4a16 -AllowBatchedVerifyDivergence
#>
[CmdletBinding()]
param(
    [string]$Model = "",   # "" = the group-matched production container (see .PARAMETER Model)
    [string]$Dflash = "",  # "" = the group-matched w4a16 drafter (see .PARAMETER Dflash)
    # Second-tier "grouping control" draft container (review fix, 2026-09-21): used ONLY when a
    # mismatch's --mtp 7 control does NOT reproduce it. A different draft container drafts a
    # DIFFERENT token sequence (same verify mechanism, different verify-window contents), so if
    # switching to it alone makes the row match --mtp 0 again, the divergence is pure verify-window
    # grouping (same class as the documented MTP mechanism), not a dflash bookkeeping bug -- a
    # bookkeeping/lifecycle bug cannot be switched off by re-quantizing the draft container.
    [string]$DflashAlt = "D:\models\r4dx\qwen38-27b-dflash2-mxfp4.r4dx",
    [string]$Layouts = "w4a16,w4a8,mxfp4",
    [int]$MaxTokens = 40,
    [switch]$AllowBatchedVerifyDivergence,
    [ValidateSet(1, 2)][int]$Tp = 1
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot\..

# ---- -Tp 2 (docs/tp.md P5): both GPUs, every r4dx-cli run under --tp 2, a TDR check after each ------
$SavedHipVisible = $env:HIP_VISIBLE_DEVICES
$SavedTpFault = $env:R4DX_TP_FAULT
$TdrCheck = Join-Path $PSScriptRoot "tp\tdr_check.ps1"
$RunStart = Get-Date
$CliErrLog = Join-Path $env:TEMP "validate_dflash.cli.err.log"  # the latest r4dx-cli run's stderr
$script:TdrSeen = $false
$TpArgs = @()
if ($Tp -eq 2) {
    $running = @(Get-Process r4dx-server -ErrorAction SilentlyContinue)
    if ($running.Count -gt 0) {
        throw "an r4dx-server is running (pid $(($running | ForEach-Object { $_.Id }) -join ', ')) -- stop it first: -Tp 2 uses both GPUs (docs/tp.md 9.2)"
    }
    $TpArgs = @("--tp", "2")  # the environment changes happen inside the try around the matrix (below)
} else {
    $env:HIP_VISIBLE_DEVICES = '1'
}

# -Tp 2, after every r4dx-cli run: the first TDR stops device-0 work (throws; the finally around the
# matrix still runs the final check). The run's own stderr is scanned first -- the P3 TDR reached HIP
# as error 719 (docs/tp.md Appendix B N44) -- then tdr_check, after 5 s for Windows Error Reporting.
# WER can log the 141 event later than that; the final check 30 s after the last run still fails the
# script then, but the next run has started (Appendix B N80).
function Assert-NoTdrYet {
    if ($Tp -ne 2) { return }
    $hip719 = @()
    if (Test-Path -LiteralPath $CliErrLog) {
        $hip719 = @(Select-String -LiteralPath $CliErrLog -Pattern 'HIP error 719\b|unspecified launch failure')
    }
    if ($hip719.Count -gt 0) {
        $script:TdrSeen = $true
        foreach ($l in $hip719) { Write-Host "  $($l.Line)" }
        throw "suspected TDR (HIP error 719 in the r4dx-cli run's stderr) -- stopping all device-0 work (no retry)"
    }
    Start-Sleep -Seconds 5
    $out = & powershell -NoProfile -ExecutionPolicy Bypass -File $TdrCheck -Since $RunStart.ToString('yyyy-MM-ddTHH:mm:ss') -Quiet
    if ($LASTEXITCODE -ne 0) {
        $script:TdrSeen = $true
        foreach ($l in @($out)) { Write-Host "  $l" }
        throw "TDR since $($RunStart.ToString('yyyy-MM-dd HH:mm:ss')) -- stopping all device-0 work (no retry)"
    }
}

# -Tp 2, from the finally around the matrix -- so on EVERY exit, a failure or Ctrl-C included: the
# final TDR check (30 s after the last run, so Windows Error Reporting has logged a late one), then the
# caller's HIP_VISIBLE_DEVICES and R4DX_TP_FAULT come back.
function Complete-TpRun {
    if ($Tp -ne 2) { return }
    Write-Host "[validate_dflash] waiting 30 s for Windows Error Reporting, then tdr_check -Since $($RunStart.ToString('yyyy-MM-dd HH:mm:ss'))"
    Start-Sleep -Seconds 30
    $out = & powershell -NoProfile -ExecutionPolicy Bypass -File $TdrCheck -Since $RunStart.ToString('yyyy-MM-ddTHH:mm:ss') -Quiet
    $rc = $LASTEXITCODE
    foreach ($l in @($out)) { Write-Output "  $l" }
    if ($rc -ne 0) {
        $script:TdrSeen = $true
        Write-Output "[validate_dflash] a TDR occurred during the run (see above)"
    }
    if ($null -ne $SavedHipVisible) { $env:HIP_VISIBLE_DEVICES = $SavedHipVisible }
    else { Remove-Item env:HIP_VISIBLE_DEVICES -ErrorAction SilentlyContinue }
    if ($null -ne $SavedTpFault) { $env:R4DX_TP_FAULT = $SavedTpFault }
    else { Remove-Item env:R4DX_TP_FAULT -ErrorAction SilentlyContinue }
}

# Every exit after the matrix goes through here: a TDR (-Tp 2) turns any exit code into 1.
function Exit-Validation([int]$code) {
    if ($script:TdrSeen) {
        Write-Output "[validate_dflash] FAILED: a TDR occurred during the run"
        $code = 1
    }
    exit $code
}

$Cli = "build\win-hip\src\cli\r4dx-cli.exe"
if (-not (Test-Path $Cli)) { throw "$Cli not found -- run .\build.ps1 first" }
# Default containers follow build\win-hip's w4a16 group (tools\r4dx_containers.ps1); an explicit
# -Model/-Dflash wins.
. (Join-Path $PSScriptRoot "r4dx_containers.ps1")
if (-not $Model) { $Model = Get-R4dxProductionTarget -BuildDir "build\win-hip" }
if (-not $Dflash) { $Dflash = Get-R4dxProductionDrafter -BuildDir "build\win-hip" }
Write-Output "[validate_dflash] target=$Model draft=$Dflash"
if (-not (Test-Path $Model)) { throw "target container not found: $Model" }
if (-not (Test-Path $Dflash)) { throw "dflash draft container not found: $Dflash" }

# Same three prompt tiers as tools/validate_fusion.ps1 (short single-chunk, ~100-token multi-chunk
# prefill, ~1000-token long-context) -- item 4's own ask ("3 prompts (short standard, ~100 tokens,
# ~1000 tokens)") is this exact grid.
$ShortPrompt = "Write a haiku about GPUs, then explain what a GPU is in two sentences."
$MediumSentence = "The GPU streams thousands of parallel threads through its compute units while " +
    "the memory controller keeps every warp fed with fresh data from high-bandwidth memory. "
$MediumPrompt = ($MediumSentence * 8) + "Summarize the paragraph above in one sentence."
$LongSentence = "In a hybrid decoder that interleaves gated linear attention with full attention " +
    "layers, the token stream is projected through quantized GEMMs at every block boundary, and " +
    "the paged KV cache stores keys and values in fp8 while the recurrent state tracks the delta " +
    "rule's running memory across chunks. "
$LongPrompt = ($LongSentence * 60) + "Summarize the paragraph above in one sentence."

$Prompts = [ordered]@{
    "short (~20 tok, single chunk)"  = $ShortPrompt
    "medium (~100 tok, multi-chunk)" = $MediumPrompt
    "long (~1000 tok, long-context)" = $LongPrompt
}
# Same reasoning as validate_fusion.ps1's own $MaxCtxByLabel comment: the "long" tier is really
# ~3500 real tokens once tokenized, not ~1000 -- 4096 leaves headroom for $MaxTokens on top.
$MaxCtxByLabel = [ordered]@{
    "short (~20 tok, single chunk)"  = 512
    "medium (~100 tok, multi-chunk)" = 512
    "long (~1000 tok, long-context)" = 4096
}

function Get-Sha256Hex([string]$text) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        return ([System.BitConverter]::ToString($sha.ComputeHash($bytes))).Replace("-", "").ToLowerInvariant()
    } finally {
        $sha.Dispose()
    }
}

# First index (0-based, UTF-16 code unit) at which $a and $b differ, or -1 if one is a prefix of
# the other, or -2 if identical.
function Find-FirstDiff([string]$a, [string]$b) {
    $n = [Math]::Min($a.Length, $b.Length)
    for ($i = 0; $i -lt $n; $i++) {
        if ($a[$i] -ne $b[$i]) { return $i }
    }
    if ($a.Length -eq $b.Length) { return -2 }
    return -1
}

function Invoke-Generation([string]$layout, [string]$prompt, [int]$maxCtx, [string]$mode,
                            [string]$draftPath = $Dflash, [double]$pMin = 0.0) {
    # r4dx-cli.exe writes its "[r4dx::model::Model] ..." load-time lines (and every "[stats]" line)
    # to stderr, not stdout (src/cli/main.cpp) -- only stdout carries the generated text this
    # function needs to hash. Same $ErrorActionPreference relaxation as validate_fusion.ps1's own
    # Invoke-Generation, for the identical reason (Windows PowerShell 5.1 turns a redirected-away
    # stderr line from a native exe into a terminating NativeCommandError under "Stop").
    # `mode`: "baseline" (--mtp 0), "dflash" (--dflash $draftPath [--dflash-p-min $pMin]), or
    # "control" (--mtp 7, the existing MTP path used ONLY to test whether a mismatch is the
    # pre-existing batched-verify mechanism -- see this script's own file comment). `draftPath`/
    # `pMin` let a mismatch's own follow-up "grouping control" (below) vary ONLY the verify-window
    # grouping (a different draft container's own drafted-token sequence, or a higher p_min early
    # stop) while holding the target/layout/prompt fixed -- the review's fix for the blocker this
    # file's own history records.
    # `$TpArgs` (-Tp 2): `--tp 2` on every mode alike, so ground truth and speculation share one engine.
    # stderr goes to $CliErrLog (overwritten per run), which Assert-NoTdrYet scans under -Tp 2.
    $prevPref = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        switch ($mode) {
            "dflash" {
                $dflashArgs = @("--dflash", $draftPath)
                if ($pMin -gt 0) { $dflashArgs += @("--dflash-p-min", "$pMin") }
                $out = & $Cli --model $Model --layout $layout --prompt $prompt --max-tokens $MaxTokens `
                    --max-ctx $maxCtx --temperature 0 @dflashArgs @TpArgs 2>$CliErrLog
            }
            "control" {
                $out = & $Cli --model $Model --layout $layout --prompt $prompt --max-tokens $MaxTokens `
                    --max-ctx $maxCtx --temperature 0 --mtp 7 @TpArgs 2>$CliErrLog
            }
            default {
                $out = & $Cli --model $Model --layout $layout --prompt $prompt --max-tokens $MaxTokens `
                    --max-ctx $maxCtx --temperature 0 --mtp 0 @TpArgs 2>$CliErrLog
            }
        }
        $exitCode = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $prevPref
    }
    Assert-NoTdrYet
    $joined = ($out -join "`n")
    if ($exitCode -ne 0) {
        throw "r4dx-cli exited $exitCode (layout=$layout max-ctx=$maxCtx mode=$mode) -- stdout was: $joined"
    }
    if ([string]::IsNullOrWhiteSpace($joined)) {
        throw "r4dx-cli produced empty stdout (layout=$layout max-ctx=$maxCtx mode=$mode) despite " +
              "exit code 0 -- refusing to hash an empty run as if it were a real result"
    }
    return $joined
}

$LayoutList = $Layouts -split ","
$results = @()
$failures = 0
$warnings = 0

$aborted = $false
try {
    if ($Tp -eq 2) {
        Remove-Item env:HIP_VISIBLE_DEVICES -ErrorAction SilentlyContinue
        # TpModel::Load arms R4DX_TP_FAULT in every --tp 2 run: never inherit one (smoke.ps1 -TpFault's).
        Remove-Item env:R4DX_TP_FAULT -ErrorAction SilentlyContinue
        Write-Output ("[validate_dflash] -Tp 2: --tp 2 on every r4dx-cli run, HIP_VISIBLE_DEVICES and R4DX_TP_FAULT " +
                      "removed (both GPUs), TDR check after every run from $($RunStart.ToString('yyyy-MM-dd HH:mm:ss'))")
    }
    foreach ($layout in $LayoutList) {
        foreach ($label in $Prompts.Keys) {
            $prompt = $Prompts[$label]
            $maxCtx = $MaxCtxByLabel[$label]
            Write-Output "[validate_dflash] layout=$layout prompt=$label max-ctx=$maxCtx ..."
            $baseline = Invoke-Generation -layout $layout -prompt $prompt -maxCtx $maxCtx -mode "baseline"
            $dflashed = Invoke-Generation -layout $layout -prompt $prompt -maxCtx $maxCtx -mode "dflash"
            $hashBase = Get-Sha256Hex $baseline
            $hashDflash = Get-Sha256Hex $dflashed
            $match = ($hashBase -eq $hashDflash)
            $status = "OK"
            $controlNote = ""
            if (-not $match) {
                $diffPos = Find-FirstDiff $baseline $dflashed
                Write-Output "  MISMATCH vs --mtp 0 -- first diff at char $diffPos"
                $ctxStart = [Math]::Max(0, $diffPos - 40)
                $ctxLen = 120
                $baseSnip = $baseline.Substring($ctxStart, [Math]::Min($ctxLen, $baseline.Length - $ctxStart))
                $dflSnip  = $dflashed.Substring($ctxStart, [Math]::Min($ctxLen, $dflashed.Length - $ctxStart))
                Write-Output "  baseline (--mtp 0) around diff: ...$baseSnip..."
                Write-Output "  dflash            around diff: ...$dflSnip..."

                # Control run: does the EXISTING, dflash-uninvolved MTP path ALSO diverge from --mtp 0
                # on this exact prompt/layout? If yes, this is the pre-existing batched-verify
                # reduction-order mechanism (docs/mtp.md), not a dflash-specific bug -- confirmed by
                # running it, not assumed from the layout name (see this script's own file comment for
                # the 2026-09-20 finding that motivated this).
                Write-Output "  running --mtp 7 control (no --dflash) to test whether this is the pre-existing batched-verify mechanism ..."
                $control = Invoke-Generation -layout $layout -prompt $prompt -maxCtx $maxCtx -mode "control"
                $hashControl = Get-Sha256Hex $control
                $controlDiverges = ($hashControl -ne $hashBase)
                $controlMatchesDflash = ($hashControl -eq $hashDflash)
                if ($controlDiverges) {
                    $controlNote = "control(--mtp 7) also diverges from --mtp 0" +
                        $(if ($controlMatchesDflash) { " AND matches --dflash exactly (same mechanism, confirmed)" } else { " (different divergence -- inspect)" })
                    if ($AllowBatchedVerifyDivergence) {
                        $status = "WARN ($controlNote)"
                        $warnings++
                    } else {
                        $status = "FAILED (control confirms batched-verify mechanism -- rerun with -AllowBatchedVerifyDivergence to accept)"
                        $failures++
                    }
                } else {
                    # Review fix (2026-09-21, blocker): the --mtp 7 control is too weak a falsifier for
                    # every case -- it changes NOTHING about DFlash2's own drafted-token sequence, so a
                    # divergence that is really "the verify window happened to group these particular
                    # tokens together" can survive it untouched. Before declaring a real bug, try a
                    # SECOND, orthogonal control that changes ONLY the grouping (a different draft
                    # container -> a different drafted-token sequence -> a different verify-window
                    # membership, still through the identical DFlash2 code path) while holding
                    # everything else fixed. A bookkeeping/lifecycle bug cannot be switched off by
                    # re-quantizing the draft container; if THIS control also fails to reproduce the
                    # divergence AND does not itself just happen to match --mtp 0 by coincidence, only
                    # then is the row a real, unexplained dflash-specific bug.
                    $controlNote = "control(--mtp 7) does NOT diverge from --mtp 0"
                    if (Test-Path $DflashAlt) {
                        Write-Output "  running grouping control (--dflash $DflashAlt, different draft container, same target/layout/prompt) ..."
                        $grouping = Invoke-Generation -layout $layout -prompt $prompt -maxCtx $maxCtx -mode "dflash" -draftPath $DflashAlt
                        $hashGrouping = Get-Sha256Hex $grouping
                        $groupingMatchesBase = ($hashGrouping -eq $hashBase)
                        if ($groupingMatchesBase) {
                            $controlNote += "; grouping control (--dflash $DflashAlt) DOES match --mtp 0 -- " +
                                "divergence is verify-window grouping (same class as the documented batched-verify " +
                                "mechanism, confirmed by an orthogonal draft-container change), not a bookkeeping bug"
                            if ($AllowBatchedVerifyDivergence) {
                                $status = "WARN ($controlNote)"
                                $warnings++
                            } else {
                                $status = "FAILED (grouping control confirms verify-window grouping -- rerun with -AllowBatchedVerifyDivergence to accept)"
                                $failures++
                            }
                        } else {
                            $controlNote += "; grouping control (--dflash $DflashAlt) ALSO diverges from --mtp 0 -- " +
                                "reproduced under an unrelated draft container, still not proven dflash-specific, but " +
                                "not cleared either -- FAILED pending investigation"
                            $status = "FAILED (unresolved -- neither control reproduces cleanly; see ControlNote)"
                            $failures++
                        }
                    } else {
                        $controlNote += " -- this mismatch is dflash-specific ($DflashAlt not found, no grouping control run)"
                        $status = "FAILED (real bug -- control did not reproduce it)"
                        $failures++
                    }
                }
                Write-Output "  $controlNote"
            } else {
                Write-Output "  OK ($hashBase)"
            }
            $results += [pscustomobject]@{
                Layout = $layout; Prompt = $label
                BaselineSha256 = $hashBase; DflashSha256 = $hashDflash; Status = $status; ControlNote = $controlNote
            }
        }
    }
} catch {
    # A failed run or (-Tp 2) a TDR: reported here; the finally still runs the final TDR check.
    Write-Output "[validate_dflash] ABORTED: $_"
    $aborted = $true
} finally {
    # A finally, not only the catch: PowerShell runs finally blocks on Ctrl-C (a pipeline stop), which
    # skips catch blocks -- an interrupted -Tp 2 run must still get the final TDR check and give the
    # caller its environment back (docs/tp.md Appendix B N80).
    Complete-TpRun
}
if ($aborted) { Exit-Validation 1 }

Write-Output ""
Write-Output "[validate_dflash] summary:"
$results | Format-Table -AutoSize | Out-String | Write-Output

if ($failures -gt 0) {
    Write-Output "[validate_dflash] FAILED: $failures / $($results.Count) combinations diverged " +
        "(not accepted as the known mxfp4 batched-reduction-order mechanism)"
    Exit-Validation 1
}
if ($warnings -gt 0) {
    Write-Output "[validate_dflash] PASSED WITH WARNINGS: $($results.Count - $warnings) byte-identical, " +
        "$warnings accepted as the known mxfp4 divergence mechanism (docs/mtp.md)"
    Exit-Validation 0
}
Write-Output "[validate_dflash] PASSED: $($results.Count) / $($results.Count) combinations byte-identical"
Exit-Validation 0
