#requires -Version 5.1
<#
.SYNOPSIS
  Mandatory end-to-end losslessness gate for SAMPLED speculative decode (docs/sampling.md sections
  9-11, Milestone 6 stage S3 item 2): proves that lifting the temperature<=0 gate on --mtp/--dflash
  produces BYTE-IDENTICAL generated text to plain sampled decode at the SAME seed and sampling
  flags, by SHA-256 of the raw generated bytes -- not a tolerance-bounded diff. Modeled directly on
  tools/validate_dflash.ps1 (same exit-code / non-empty-stdout / pinned --max-ctx handling, same
  reason for each, same "accept a mismatch only through an explicit, logged control" contract -- see
  that script's own comments for the review findings that shaped it), extended with the two axes
  that only exist for sampled decode: a sampling config (temperature/top_k/top_p) and a seed.

.DESCRIPTION
  The losslessness argument (docs/sampling.md design point D, "sample-and-match" rejection
  sampling): a greedy drafter's proposal distribution is a point mass on its drafted token x, so
  drawing y ~ p once and accepting iff y == x is EXACTLY the standard rejection-sampling accept
  rule, and because exactly one draw is consumed per EMITTED token (never per drafted token), the
  emitted sequence for a fixed seed is identical, token for token, to plain sampled decode from the
  same prompt -- PROVIDED the round's own verify pass computed the same row sequential single-row
  decode would have (see the next paragraph for when it does not). This script is the repeatable,
  real-hardware regression gate for that argument: for every (target layout, prompt, sampling
  config, seed) combination, runs r4dx-cli.exe three ways against the same real target container --
  plain (no --mtp/--dflash, the ground truth), `--mtp 3`, and `--dflash <draft> --dflash-k 7` -- and
  compares SHA-256 of each pair's raw stdout.

  KNOWN, DOCUMENTED, NON-BUG divergence mechanism (docs/sampling.md section 9.3, same mechanism
  tools/validate_dflash.ps1 already documents for greedy MTP): a speculative round computes its
  logits in one q_len>1 batched-verify pass whose floating-point reduction order differs from
  single-row sequential decode's, which a greedy argmax usually survives but a CDF walk does not,
  because the same numeric perturbation can move a candidate boundary by ~1e-2 of the distribution's
  mass right where two candidates are nearly tied. At this container's base divergence rate (most
  sampled trajectories diverge from plain decode SOMEWHERE), "a control also diverges from the
  baseline" is true almost by default and has essentially no power to separate the known mechanism
  from a real bug (review finding, 2026-09-21) -- so this script does NOT accept on that basis. On
  any baseline-vs-speculative mismatch it (a) prints a character-level diff position and both texts'
  prefixes, then (b) tries, in order, up to two controls at the SAME seed/prompt/layout/sampling-
  config, and accepts ONLY if a control's hash EXACTLY MATCHES the speculative run's own hash (not
  merely "diverges from baseline" -- matching the mismatched target exactly is the only evidence
  that the SAME mechanism produced the SAME token sequence): a CROSS-FAMILY control first
  (`--dflash` for an `--mtp 3` mismatch, `--mtp 7` for a `--dflash` mismatch), then, if that does not
  match exactly, a SAME-FAMILY "grouping" control that changes only what the verify window contains
  without touching the mismatching family's own bookkeeping (`--mtp 7` in place of `--mtp 3` for an
  `--mtp` mismatch -- same code path, different k, so a real bookkeeping bug cannot be switched off
  by it; a different draft container, `-DflashAlt`, in place of the default draft for a `--dflash`
  mismatch -- same code path, different drafted-token sequence, mirroring
  `tools/validate_dflash.ps1`'s own second-tier grouping control). Only when one of the two controls
  matches the target's hash exactly (still requires -AllowBatchedVerifyDivergence, a human decision,
  not a default) is the row downgraded to WARN; a mismatch neither control reproduces exactly is a
  hard FAILED regardless of the switch, reported honestly rather than downgraded.

.PARAMETER Model
  Path to the real 64-layer target container. Default: the production container matching build\win-hip's w4a16 group,
  read from build\win-hip\CMakeCache.txt (R4DX_W4A16_GROUP) by tools\r4dx_containers.ps1: group 64
  (the default build) -> D:\models\r4dx\qwen38-27b-v6.r4dx, group 128 -> D:\models\r4dx\qwen38-27b-v3.r4dx.

.PARAMETER Dflash
  Path to the DFlash2 draft container to test. Default: the w4a16 draft container matching the same group -- group 64 ->
  D:\models\r4dx\qwen38-27b-dflash2-w4a16-g64.r4dx, group 128 -> D:\models\r4dx\qwen38-27b-dflash2-w4a16.r4dx.

.PARAMETER DflashAlt
  Second-tier "grouping control" draft container (review fix, 2026-09-21), mirroring
  tools/validate_dflash.ps1's own -DflashAlt: used ONLY when a --dflash mismatch's cross-family
  (--mtp 7) control does not match the mismatch's own hash exactly. A different draft container
  drafts a different token sequence through the identical DFlash2 code path (same verify mechanism,
  different verify-window contents), so if switching to it reproduces the ORIGINAL --dflash run's
  own hash, the divergence is pure verify-window grouping, not a dflash-specific bookkeeping bug --
  a bookkeeping/lifecycle bug cannot be switched off by re-quantizing the draft container. Default:
  the mxfp4 draft container (independent of the w4a16 default above).

.PARAMETER Layouts
  Comma-separated TARGET body layouts. Default: w4a16,w4a8,mxfp4 (bf16 excluded, standing
  bf16-retired-from-perf-work rule -- docs/status.md).

.PARAMETER Seeds
  Comma-separated seeds. Default: 1,2 (the task's own ask).

.PARAMETER MaxTokens
  --max-tokens for every generation. Default 48: long enough to exercise several verify rounds at
  k=3/k=7 without making the full matrix (3 layouts x 2 prompts x 3 sampling configs x 2 seeds x 3
  modes = 108 generations) too slow to actually run.

.PARAMETER Quick
  Restricts Layouts to w4a16 only (a fast smoke pass -- CI/pre-flight use, not the mandatory gate).

.PARAMETER AllowBatchedVerifyDivergence
  If set, a mismatch is downgraded from FAILED to WARN IF AND ONLY IF one of the two controls (see
  .DESCRIPTION) at the SAME seed/prompt/layout/sampling-config matches the mismatch's OWN hash
  exactly. A mismatch neither control reproduces exactly is a hard FAILED regardless of this switch.

.PARAMETER Tp
  Tensor parallelism (docs/tp.md P5, gate G12): 1 (default) runs everything on HIP device 1, exactly
  as before this parameter existed. 2 passes `--tp 2` (real mode, both GPUs) to EVERY r4dx-cli run --
  the plain sampled ground truth, both speculative modes and every control alike, so every comparison
  is TP=2 against TP=2 -- and REMOVES HIP_VISIBLE_DEVICES and R4DX_TP_FAULT for the run (both
  restored at the end, from a finally: an error or Ctrl-C restores them too). It refuses to start
  while an r4dx-server is running (docs/tp.md 9.2); after every run it scans that run's stderr for HIP
  error 719 and, 5 s later, checks for a device-0 TDR (tools\tp\tdr_check.ps1, Appendix B N55),
  stopping at the first one (no retry); and on every exit it runs the check once more 30 s after the
  last run. A TDR fails the script (exit 1). An MTP FAILED row at -Tp 2 is ambiguous on its own: the
  known test_mtp CheckSampledRoundsMatchPlain [w4a16] failure (0/18 identical sampled trajectories at
  TP=1, Appendix B N29) is this property -- run the same matrix at -Tp 1 on the same tree before
  blaming TP (Appendix B N80).

.EXAMPLE
  .\tools\validate_spec_sampling.ps1
.EXAMPLE
  .\tools\validate_spec_sampling.ps1 -Quick -AllowBatchedVerifyDivergence
.EXAMPLE
  .\tools\validate_spec_sampling.ps1 -Tp 2 -Layouts w4a16 -AllowBatchedVerifyDivergence
#>
[CmdletBinding()]
param(
    [string]$Model = "",   # "" = the group-matched production container (see .PARAMETER Model)
    [string]$Dflash = "",  # "" = the group-matched w4a16 drafter (see .PARAMETER Dflash)
    [string]$DflashAlt = "D:\models\r4dx\qwen38-27b-dflash2-mxfp4.r4dx",
    [string]$Layouts = "w4a16,w4a8,mxfp4",
    [string]$Seeds = "1,2",
    [int]$MaxTokens = 48,
    [switch]$Quick,
    [switch]$AllowBatchedVerifyDivergence,
    [ValidateSet(1, 2)][int]$Tp = 1
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot\..

# ---- -Tp 2 (docs/tp.md P5): both GPUs, every r4dx-cli run under --tp 2, a TDR check after each ------
# Same helpers as tools/validate_dflash.ps1's (see its comments).
$SavedHipVisible = $env:HIP_VISIBLE_DEVICES
$SavedTpFault = $env:R4DX_TP_FAULT
$TdrCheck = Join-Path $PSScriptRoot "tp\tdr_check.ps1"
$RunStart = Get-Date
$CliErrLog = Join-Path $env:TEMP "validate_spec_sampling.cli.err.log"  # the latest r4dx-cli run's stderr
$script:TdrSeen = $false
$TpArgs = @()
if ($Tp -eq 2) {
    $running = @(Get-Process r4dx-server -ErrorAction SilentlyContinue)
    if ($running.Count -gt 0) {
        throw "an r4dx-server is running (pid $(($running | ForEach-Object { $_.Id }) -join ', ')) -- stop it first: -Tp 2 uses both GPUs (docs/tp.md 9.2)"
    }
    $TpArgs = @("--tp", "2")  # the environment changes happen inside the try around the matrix (below)
} else {
    $env:HIP_VISIBLE_DEVICES = '1'
}

# -Tp 2, after every r4dx-cli run: HIP error 719 in its stderr, then (5 s later) tdr_check; the first
# TDR stops device-0 work (throws; the finally around the matrix still runs the final check).
function Assert-NoTdrYet {
    if ($Tp -ne 2) { return }
    $hip719 = @()
    if (Test-Path -LiteralPath $CliErrLog) {
        $hip719 = @(Select-String -LiteralPath $CliErrLog -Pattern 'HIP error 719\b|unspecified launch failure')
    }
    if ($hip719.Count -gt 0) {
        $script:TdrSeen = $true
        foreach ($l in $hip719) { Write-Host "  $($l.Line)" }
        throw "suspected TDR (HIP error 719 in the r4dx-cli run's stderr) -- stopping all device-0 work (no retry)"
    }
    Start-Sleep -Seconds 5
    $out = & powershell -NoProfile -ExecutionPolicy Bypass -File $TdrCheck -Since $RunStart.ToString('yyyy-MM-ddTHH:mm:ss') -Quiet
    if ($LASTEXITCODE -ne 0) {
        $script:TdrSeen = $true
        foreach ($l in @($out)) { Write-Host "  $l" }
        throw "TDR since $($RunStart.ToString('yyyy-MM-dd HH:mm:ss')) -- stopping all device-0 work (no retry)"
    }
}

# -Tp 2, from the finally around the matrix (every exit, a failure or Ctrl-C included): the final TDR
# check 30 s after the last run, then the caller's HIP_VISIBLE_DEVICES and R4DX_TP_FAULT come back.
function Complete-TpRun {
    if ($Tp -ne 2) { return }
    Write-Host "[validate_spec_sampling] waiting 30 s for Windows Error Reporting, then tdr_check -Since $($RunStart.ToString('yyyy-MM-dd HH:mm:ss'))"
    Start-Sleep -Seconds 30
    $out = & powershell -NoProfile -ExecutionPolicy Bypass -File $TdrCheck -Since $RunStart.ToString('yyyy-MM-ddTHH:mm:ss') -Quiet
    $rc = $LASTEXITCODE
    foreach ($l in @($out)) { Write-Output "  $l" }
    if ($rc -ne 0) {
        $script:TdrSeen = $true
        Write-Output "[validate_spec_sampling] a TDR occurred during the run (see above)"
    }
    if ($null -ne $SavedHipVisible) { $env:HIP_VISIBLE_DEVICES = $SavedHipVisible }
    else { Remove-Item env:HIP_VISIBLE_DEVICES -ErrorAction SilentlyContinue }
    if ($null -ne $SavedTpFault) { $env:R4DX_TP_FAULT = $SavedTpFault }
    else { Remove-Item env:R4DX_TP_FAULT -ErrorAction SilentlyContinue }
}

# Every exit after the matrix goes through here: a TDR (-Tp 2) turns any exit code into 1.
function Exit-Validation([int]$code) {
    if ($script:TdrSeen) {
        Write-Output "[validate_spec_sampling] FAILED: a TDR occurred during the run"
        $code = 1
    }
    exit $code
}

$Cli = "build\win-hip\src\cli\r4dx-cli.exe"
if (-not (Test-Path $Cli)) { throw "$Cli not found -- run .\build.ps1 first" }
# Default containers follow build\win-hip's w4a16 group (tools\r4dx_containers.ps1); an explicit
# -Model/-Dflash wins.
. (Join-Path $PSScriptRoot "r4dx_containers.ps1")
if (-not $Model) { $Model = Get-R4dxProductionTarget -BuildDir "build\win-hip" }
if (-not $Dflash) { $Dflash = Get-R4dxProductionDrafter -BuildDir "build\win-hip" }
Write-Output "[validate_spec_sampling] target=$Model draft=$Dflash"
if (-not (Test-Path $Model)) { throw "target container not found: $Model" }
if (-not (Test-Path $Dflash)) { throw "dflash draft container not found: $Dflash" }
$HasDflashAlt = Test-Path $DflashAlt
if (-not $HasDflashAlt) {
    Write-Output "[validate_spec_sampling] WARNING: grouping-control draft container not found ($DflashAlt) -- a --dflash mismatch whose cross-family control does not match exactly will have no second-tier control to try"
}

if ($Quick) { $Layouts = "w4a16" }

# Same standard prompt as tools/validate_dflash.ps1 and docs/perf.md's own measurement prompt.
$StandardPrompt = "Write a haiku about GPUs, then explain what a GPU is in two sentences."

# ~270-token code prompt (task item 2's own ask): a short code excerpt plus a review question,
# built the same "repeat a fixed sentence" way validate_dflash.ps1's own $MediumPrompt/$LongPrompt
# are, so its approximate token count is reproducible rather than hand-counted.
$CodeSentence = "def process_batch(items, batch_size=32, transform=None):`n" +
    "    results = []`n" +
    "    for i in range(0, len(items), batch_size):`n" +
    "        chunk = items[i:i + batch_size]`n" +
    "        if transform is not None:`n" +
    "            chunk = [transform(x) for x in chunk]`n" +
    "        results.extend(chunk)`n" +
    "    return results`n`n"
$CodePrompt = ($CodeSentence * 4) +
    "Review the Python function above: explain what it does, point out one edge case it does " +
    "not handle, and suggest one concrete change to fix it."

$Prompts = [ordered]@{
    "standard (haiku, ~20 tok)" = @{ Text = $StandardPrompt; MaxCtx = 512 }
    "code (~270 tok)"           = @{ Text = $CodePrompt; MaxCtx = 1024 }
}

# Task item 2's own three sampling configs.
$SamplingConfigs = [ordered]@{
    "T=0.7 top_k=20 top_p=0.8" = @{ Temperature = 0.7; TopK = 20; TopP = 0.8; MinP = 0.0 }
    "T=1.0 pure"               = @{ Temperature = 1.0; TopK = 0;  TopP = 1.0; MinP = 0.0 }
    "T=0.6 top_k=20 top_p=0.95" = @{ Temperature = 0.6; TopK = 20; TopP = 0.95; MinP = 0.0 }
}

function Get-Sha256Hex([string]$text) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        return ([System.BitConverter]::ToString($sha.ComputeHash($bytes))).Replace("-", "").ToLowerInvariant()
    } finally {
        $sha.Dispose()
    }
}

# First index (0-based, UTF-16 code unit) at which $a and $b differ, or -1 if one is a prefix of
# the other, or -2 if identical.
function Find-FirstDiff([string]$a, [string]$b) {
    $n = [Math]::Min($a.Length, $b.Length)
    for ($i = 0; $i -lt $n; $i++) {
        if ($a[$i] -ne $b[$i]) { return $i }
    }
    if ($a.Length -eq $b.Length) { return -2 }
    return -1
}

# `mode`: "baseline" (no --mtp/--dflash, plain sampled decode), "mtp" (--mtp 3), "dflash"
# (--dflash $draftPath --dflash-k 7), "control-mtp7" (--mtp 7 -- the cross-family control for a
# --dflash mismatch, AND the same-family "grouping" control for an --mtp mismatch: same code path,
# different k, so it cannot be switched off by a --mtp-specific bookkeeping bug), or "dflash-alt"
# (--dflash $draftPath --dflash-k 7 with `draftPath` overridden to a DIFFERENT draft container --
# the same-family grouping control for a --dflash mismatch, mirroring tools/validate_dflash.ps1's
# own -DflashAlt). Every mode shares the same --temperature/--top-k/--top-p/--seed, so the ONLY
# thing that differs between baseline and a speculative mode is whether/which drafter ran -- exactly
# the comparison the losslessness gate needs.
function Invoke-Generation([string]$layout, [string]$prompt, [int]$maxCtx, [hashtable]$cfg,
                            [int]$seed, [string]$mode, [string]$draftPath = $Dflash) {
    $commonArgs = @(
        "--model", $Model, "--layout", $layout, "--prompt", $prompt,
        "--max-tokens", $MaxTokens, "--max-ctx", $maxCtx,
        "--temperature", $cfg.Temperature, "--top-k", $cfg.TopK, "--top-p", $cfg.TopP,
        "--min-p", $cfg.MinP, "--seed", $seed
    )
    $modeArgs = switch ($mode) {
        "mtp"          { @("--mtp", 3) }
        "dflash"       { @("--dflash", $draftPath, "--dflash-k", 7) }
        "dflash-alt"   { @("--dflash", $draftPath, "--dflash-k", 7) }
        "control-mtp7" { @("--mtp", 7) }
        default        { @() }
    }
    # r4dx-cli.exe writes its load-time/[stats] lines to stderr, not stdout (src/cli/main.cpp) --
    # only stdout carries the generated text this function needs to hash. Same $ErrorActionPreference
    # relaxation as validate_dflash.ps1's own Invoke-Generation, for the identical reason (Windows
    # PowerShell 5.1 turns a redirected-away stderr line from a native exe into a terminating
    # NativeCommandError under "Stop"). `$TpArgs` (-Tp 2): `--tp 2` on every mode alike. stderr goes to
    # $CliErrLog (overwritten per run), which Assert-NoTdrYet scans under -Tp 2.
    $prevPref = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $out = & $Cli @commonArgs @modeArgs @TpArgs 2>$CliErrLog
        $exitCode = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $prevPref
    }
    Assert-NoTdrYet
    $joined = ($out -join "`n")
    if ($exitCode -ne 0) {
        throw "r4dx-cli exited $exitCode (layout=$layout max-ctx=$maxCtx mode=$mode seed=$seed) -- stdout was: $joined"
    }
    if ([string]::IsNullOrWhiteSpace($joined)) {
        throw "r4dx-cli produced empty stdout (layout=$layout max-ctx=$maxCtx mode=$mode seed=$seed) despite " +
              "exit code 0 -- refusing to hash an empty run as if it were a real result"
    }
    return $joined
}

# Runs one baseline-vs-speculative comparison, trying up to two controls on a mismatch.
# `targetMode`: "mtp" or "dflash". `controls`: an ordered array of @{Mode=;Label=;DraftPath=} --
# tried in order, and the row is accepted (WARN) at the FIRST control whose hash matches the
# MISMATCH'S OWN hash exactly (review fix, 2026-09-21: "also diverges from baseline" is not
# evidence at this container's base divergence rate -- only reproducing the SAME token sequence is).
# Tier 1 is always a cross-family control (changes which speculative code path ran, not its
# parameters); tier 2 is a same-family "grouping" control (changes only the verify window's
# contents -- a different k, or a different draft container -- so a real bookkeeping bug in the
# mismatching family's own code cannot be switched off by it).
function Test-OneCombination([string]$layout, [string]$promptLabel, [string]$prompt, [int]$maxCtx,
                              [string]$cfgLabel, [hashtable]$cfg, [int]$seed,
                              [string]$targetMode, [string]$targetLabel, [array]$controls,
                              [string]$baseline, [string]$hashBase) {
    $speculative = Invoke-Generation -layout $layout -prompt $prompt -maxCtx $maxCtx -cfg $cfg -seed $seed -mode $targetMode
    $hashSpec = Get-Sha256Hex $speculative
    $match = ($hashBase -eq $hashSpec)
    $status = "OK"
    $note = ""
    if (-not $match) {
        # Write-Host (not Write-Output) for every diagnostic line in this function: this function's
        # RETURN VALUE is captured by the caller via `$results += Test-OneCombination ...`, and in
        # PowerShell that capture grabs EVERYTHING written to the success/output stream inside the
        # function, not just the final `return` -- a stray `Write-Output` here would silently splice
        # extra string elements into $results alongside the real pscustomobject rows, corrupting the
        # summary table and the failure/warning counts. Write-Host targets the separate Information
        # stream instead: still visible on console and still captured by the caller script's own
        # `*>&1 | Tee-Object` redirection, but invisible to a variable-assignment capture.
        $diffPos = Find-FirstDiff $baseline $speculative
        Write-Host "  MISMATCH ($targetLabel) vs baseline -- first diff at char $diffPos"
        $ctxStart = [Math]::Max(0, $diffPos - 40)
        $ctxLen = 120
        $baseSnip = $baseline.Substring($ctxStart, [Math]::Min($ctxLen, $baseline.Length - $ctxStart))
        $specSnip = $speculative.Substring($ctxStart, [Math]::Min($ctxLen, $speculative.Length - $ctxStart))
        Write-Host "  baseline        around diff: ...$baseSnip..."
        Write-Host "  $targetLabel around diff: ...$specSnip..."
        $resolvedBy = $null
        $notes = @()
        foreach ($ctrl in $controls) {
            if ($ctrl.ContainsKey("SkipIf") -and (& $ctrl.SkipIf)) {
                $notes += "$($ctrl.Label) control skipped ($($ctrl.SkipReason))"
                continue
            }
            Write-Host "  running $($ctrl.Label) control (same seed/prompt/layout/sampling) ..."
            $ctrlArgs = @{ layout = $layout; prompt = $prompt; maxCtx = $maxCtx; cfg = $cfg; seed = $seed; mode = $ctrl.Mode }
            if ($ctrl.ContainsKey("DraftPath")) { $ctrlArgs.draftPath = $ctrl.DraftPath }
            $control = Invoke-Generation @ctrlArgs
            $hashControl = Get-Sha256Hex $control
            $controlDiverges = ($hashControl -ne $hashBase)
            $controlMatchesTarget = ($hashControl -eq $hashSpec)
            if ($controlMatchesTarget) {
                $notes += "$($ctrl.Label) control MATCHES $targetLabel exactly (same mechanism, confirmed)"
                $resolvedBy = $ctrl.Label
                break
            } else {
                $notes += "$($ctrl.Label) control does NOT match $targetLabel" +
                    $(if ($controlDiverges) { " (diverges from baseline too, but a different divergence -- not proof)" } else { " (matches baseline instead -- this control did not reproduce it)" })
            }
        }
        $note = $notes -join "; "
        if ($resolvedBy) {
            if ($AllowBatchedVerifyDivergence) {
                $status = "WARN (resolved by $resolvedBy control -- $note)"
            } else {
                $status = "FAILED ($resolvedBy control confirms batched-verify mechanism -- rerun with -AllowBatchedVerifyDivergence to accept)"
            }
        } else {
            $status = "FAILED (real bug or unresolved -- no control reproduced this mismatch exactly -- $note)"
        }
        Write-Host "  $note"
    } else {
        Write-Host "  OK ($targetLabel matches baseline, $hashBase)"
    }
    return [pscustomobject]@{
        Layout = $layout; Prompt = $promptLabel; Sampling = $cfgLabel; Seed = $seed; Mode = $targetLabel
        BaselineSha256 = $hashBase; ModeSha256 = $hashSpec; Status = $status; Note = $note
    }
}

$LayoutList = $Layouts -split ","
$SeedList = ($Seeds -split ",") | ForEach-Object { [int]$_ }
$results = @()
$failures = 0
$warnings = 0

$aborted = $false
try {
    if ($Tp -eq 2) {
        Remove-Item env:HIP_VISIBLE_DEVICES -ErrorAction SilentlyContinue
        # TpModel::Load arms R4DX_TP_FAULT in every --tp 2 run: never inherit one (smoke.ps1 -TpFault's).
        Remove-Item env:R4DX_TP_FAULT -ErrorAction SilentlyContinue
        Write-Output ("[validate_spec_sampling] -Tp 2: --tp 2 on every r4dx-cli run, HIP_VISIBLE_DEVICES and " +
                      "R4DX_TP_FAULT removed (both GPUs), TDR check after every run from " +
                      "$($RunStart.ToString('yyyy-MM-dd HH:mm:ss'))")
    }
    foreach ($layout in $LayoutList) {
        foreach ($promptLabel in $Prompts.Keys) {
            $promptInfo = $Prompts[$promptLabel]
            foreach ($cfgLabel in $SamplingConfigs.Keys) {
                $cfg = $SamplingConfigs[$cfgLabel]
                foreach ($seed in $SeedList) {
                    Write-Output "[validate_spec_sampling] layout=$layout prompt=$promptLabel sampling=$cfgLabel seed=$seed ..."
                    $baseline = Invoke-Generation -layout $layout -prompt $promptInfo.Text -maxCtx $promptInfo.MaxCtx `
                        -cfg $cfg -seed $seed -mode "baseline"
                    $hashBase = Get-Sha256Hex $baseline

                    $mtpControls = @(
                        @{ Mode = "dflash"; Label = "--dflash k=7 (cross-family)" }
                        @{ Mode = "control-mtp7"; Label = "--mtp 7 (same-family grouping)" }
                    )
                    $results += Test-OneCombination -layout $layout -promptLabel $promptLabel -prompt $promptInfo.Text `
                        -maxCtx $promptInfo.MaxCtx -cfgLabel $cfgLabel -cfg $cfg -seed $seed `
                        -targetMode "mtp" -targetLabel "--mtp 3" -controls $mtpControls `
                        -baseline $baseline -hashBase $hashBase

                    $dflashControls = @(
                        @{ Mode = "control-mtp7"; Label = "--mtp 7 (cross-family)" }
                        @{ Mode = "dflash-alt"; Label = "--dflash $DflashAlt (same-family grouping)"; DraftPath = $DflashAlt
                           SkipIf = { -not $HasDflashAlt }; SkipReason = "$DflashAlt not found" }
                    )
                    $results += Test-OneCombination -layout $layout -promptLabel $promptLabel -prompt $promptInfo.Text `
                        -maxCtx $promptInfo.MaxCtx -cfgLabel $cfgLabel -cfg $cfg -seed $seed `
                        -targetMode "dflash" -targetLabel "--dflash k=7" -controls $dflashControls `
                        -baseline $baseline -hashBase $hashBase
                }
            }
        }
    }
} catch {
    # A failed run or (-Tp 2) a TDR: reported here; the finally still runs the final TDR check.
    Write-Output "[validate_spec_sampling] ABORTED: $_"
    $aborted = $true
} finally {
    # A finally, not only the catch: Ctrl-C skips catch blocks but runs finally blocks (docs/tp.md
    # Appendix B N80).
    Complete-TpRun
}
if ($aborted) { Exit-Validation 1 }

foreach ($r in $results) {
    if ($r.Status -like "FAILED*") { $failures++ }
    elseif ($r.Status -like "WARN*") { $warnings++ }
}

Write-Output ""
Write-Output "[validate_spec_sampling] summary:"
$results | Format-Table -AutoSize | Out-String | Write-Output

if ($failures -gt 0) {
    Write-Output "[validate_spec_sampling] FAILED: $failures / $($results.Count) combinations diverged (not accepted as the known batched-verify mechanism)"
    Exit-Validation 1
}
if ($warnings -gt 0) {
    Write-Output "[validate_spec_sampling] PASSED WITH WARNINGS: $($results.Count - $warnings) byte-identical, $warnings accepted as the known batched-verify divergence mechanism (docs/sampling.md section 9.3)"
    Exit-Validation 0
}
Write-Output "[validate_spec_sampling] PASSED: $($results.Count) / $($results.Count) combinations byte-identical"
Exit-Validation 0
