#requires -Version 5.1
<#
.SYNOPSIS
  Mandatory end-to-end correctness gate for the R2/P2 fused activation-quant epilogues
  (docs/r9700.md R2/P2, docs/status.md's "R2/P2 fused activation-quant epilogues" section): proves
  the fused-producer code path (src/model/linear.cpp's EpilogueForLayout) produces BYTE-IDENTICAL
  generated text to the fusion-disabled baseline, by SHA-256 of the raw generated bytes -- not a
  tolerance-bounded diff.

.DESCRIPTION
  tests/kernels/test_fused_quant.cpp's tolerance-free 135-check byte-diff grid (plus its
  ArenaAlignmentInvariant addition) verifies the fused epilogue KERNELS and the Arena allocator in
  isolation, but neither one exercises a real end-to-end forward pass through the whole model --
  that is exactly the gap that let the original R2/P2 incident (docs/status.md) ship a real
  generated-text divergence past every ctest golden. This script is the repeatable, real-hardware
  regression gate for anything that touches src/model/linear.cpp, src/core/arena.hpp, or
  src/kernels/src/r4dx_kernels.hip's epilogue code from here on.

  For every (layout, prompt length, --mtp) combination, runs r4dx-cli.exe TWICE against the same
  real container -- once with R4DX_DISABLE_EPILOGUE=1 (forces EpilogueForLayout back to
  r4dx_epilogue_none for every layout, i.e. the pre-fusion baseline) and once with it unset (today's
  shipped behavior: fused for w4a8/mxfp4, still unfused for w4a16/bf16 -- see linear.cpp's own
  EpilogueForLayout comment for why w4a16 stays off) -- and compares the SHA-256 of the two runs'
  raw stdout (the generated text only; r4dx-cli's `[stats]`/VRAM/`--profile` lines all go to
  stderr, not stdout -- see src/cli/main.cpp -- so no filtering is needed).

  Covers all three layouts the task asks for (w4a16, w4a8, mxfp4 -- bf16 excluded, same standing
  rule as every other perf/correctness pass: docs/r9700.md retires bf16 from perf work, and
  EpilogueForLayout never fuses it in the first place, so its row would be a trivial no-op check),
  three prompt lengths (short single-chunk, ~100-token multi-chunk, ~1000-token long-context), and
  both --mtp 0 and --mtp 3 -- the task's own required grid. w4a16 is expected to be byte-identical
  trivially (EpilogueForLayout returns r4dx_epilogue_none for it either way) -- kept in the grid as
  a regression check that flipping the env var alone never perturbs it.

.PARAMETER Model
  Path to a .r4dx container with mtp.* weights (required for the --mtp 3 rows). Default: the production container matching build\win-hip's w4a16 group,
  read from build\win-hip\CMakeCache.txt (R4DX_W4A16_GROUP) by tools\r4dx_containers.ps1: group 64
  (the default build) -> D:\models\r4dx\qwen38-27b-v6.r4dx, group 128 -> D:\models\r4dx\qwen38-27b-v3.r4dx.

.PARAMETER Layouts
  Comma-separated layout list. Default: w4a16,w4a8,mxfp4 (bf16 excluded, see above).

.PARAMETER MaxTokens
  --max-tokens for every generation. Default 40 -- long enough to exercise several decode/MTP-verify
  rounds without making the full matrix (layouts x prompts x mtp x on/off = 36 runs) slow.

.EXAMPLE
  .\tools\validate_fusion.ps1
.EXAMPLE
  .\tools\validate_fusion.ps1 -Layouts w4a8,mxfp4 -MaxTokens 24
#>
[CmdletBinding()]
param(
    [string]$Model = "",  # "" = the group-matched production container (see .PARAMETER Model)
    [string]$Layouts = "w4a16,w4a8,mxfp4",
    [int]$MaxTokens = 40
)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot\..
$env:HIP_VISIBLE_DEVICES = '1'

$Cli = "build\win-hip\src\cli\r4dx-cli.exe"
if (-not (Test-Path $Cli)) { throw "$Cli not found -- run .\build.ps1 first" }
# Default containers follow build\win-hip's w4a16 group (tools\r4dx_containers.ps1); an explicit
# -Model/-Dflash wins.
. (Join-Path $PSScriptRoot "r4dx_containers.ps1")
if (-not $Model) { $Model = Get-R4dxProductionTarget -BuildDir "build\win-hip" }
Write-Output "[validate_fusion] model=$Model"
if (-not (Test-Path $Model)) { throw "model container not found: $Model" }

# Three prompt lengths (task requirement): short single-chunk, ~100-token multi-chunk prefill,
# ~1000-token long-context (several 64-token prefill chunks -- docs/architecture.md's "Interim
# chunked prefill").
$ShortPrompt = "Write a haiku about GPUs, then explain what a GPU is in two sentences."
$MediumSentence = "The GPU streams thousands of parallel threads through its compute units while " +
    "the memory controller keeps every warp fed with fresh data from high-bandwidth memory. "
$MediumPrompt = ($MediumSentence * 8) + "Summarize the paragraph above in one sentence."
$LongSentence = "In a hybrid decoder that interleaves gated linear attention with full attention " +
    "layers, the token stream is projected through quantized GEMMs at every block boundary, and " +
    "the paged KV cache stores keys and values in fp8 while the recurrent state tracks the delta " +
    "rule's running memory across chunks. "
$LongPrompt = ($LongSentence * 60) + "Summarize the paragraph above in one sentence."

$Prompts = [ordered]@{
    "short (~20 tok, single chunk)"  = $ShortPrompt
    "medium (~100 tok, multi-chunk)" = $MediumPrompt
    "long (~1000 tok, long-context)" = $LongPrompt
}

# Explicit --max-ctx per prompt tier (review finding, 2026-09-20): this script previously passed
# no --max-ctx at all, silently inheriting r4dx-cli's own default -- which the "Long-context
# validation" pass changed 131072 -> 262144, making every row here allocate 8.3 GiB of KV it does
# not need. Pinned here so this gate's own resource footprint and behavior are independent of
# whatever the CLI's default happens to be at any given time. The "long" tier's own label/comment
# says "~1000 tok" but the real tokenizer puts $LongPrompt at 3502 tokens (measured directly,
# --stats, 2026-09-20) -- an easy trap the previous fully-silent-failure bug (this same finding)
# would have hidden completely: 2048 is NOT enough headroom and every long-tier row would have
# failed with "PagedKvCache: start_pos+T exceeds the max_context_tokens this cache was sized for"
# while still reporting a false "OK" match on two empty stdouts. 4096 leaves headroom for
# $MaxTokens on top of the real 3502-token prompt.
$MaxCtxByLabel = [ordered]@{
    "short (~20 tok, single chunk)"  = 512
    "medium (~100 tok, multi-chunk)" = 512
    "long (~1000 tok, long-context)" = 4096
}

function Get-Sha256Hex([string]$text) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($text)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        return ([System.BitConverter]::ToString($sha.ComputeHash($bytes))).Replace("-", "").ToLowerInvariant()
    } finally {
        $sha.Dispose()
    }
}

function Invoke-Generation([string]$layout, [string]$prompt, [int]$mtp, [bool]$disableEpilogue, [int]$maxCtx) {
    if ($disableEpilogue) { $env:R4DX_DISABLE_EPILOGUE = '1' } else { Remove-Item Env:R4DX_DISABLE_EPILOGUE -ErrorAction SilentlyContinue }
    # r4dx-cli.exe writes its "[r4dx::model::Model] VRAM breakdown" load-time line (and every
    # "[stats]" line) to stderr, not stdout (src/cli/main.cpp) -- only stdout carries the generated
    # text this function needs to hash. Windows PowerShell 5.1, with $ErrorActionPreference="Stop"
    # (set at this script's top), turns EVERY stderr line from a native exe into a terminating
    # NativeCommandError even when that stream is redirected to $null, unless the preference is
    # relaxed for the duration of the call -- so it's relaxed here, not globally, to keep the rest
    # of this script's own cmdlet errors fail-fast.
    #
    # Review finding, 2026-09-20: this function previously discarded stderr, never checked
    # $LASTEXITCODE, and never asserted stdout was non-empty -- two runs that both silently FAILED
    # (e.g. r4dx-cli exiting 1 because the prompt exceeded --max-ctx) produced identical empty
    # stdout, whose SHA-256 matched and got reported "OK". Both a non-zero exit code and empty
    # stdout are now hard failures, not silent false-passes.
    $prevPref = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $out = & $Cli --model $Model --layout $layout --prompt $prompt --max-tokens $MaxTokens `
            --max-ctx $maxCtx --temperature 0 --mtp $mtp 2>$null
        $exitCode = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $prevPref
    }
    Remove-Item Env:R4DX_DISABLE_EPILOGUE -ErrorAction SilentlyContinue
    $joined = ($out -join "`n")
    if ($exitCode -ne 0) {
        throw "r4dx-cli exited $exitCode (layout=$layout mtp=$mtp max-ctx=$maxCtx disableEpilogue=$disableEpilogue) -- " +
              "stdout was: $joined"
    }
    if ([string]::IsNullOrWhiteSpace($joined)) {
        throw "r4dx-cli produced empty stdout (layout=$layout mtp=$mtp max-ctx=$maxCtx disableEpilogue=$disableEpilogue) " +
              "despite exit code 0 -- refusing to hash an empty run as if it were a real result"
    }
    return $joined
}

$LayoutList = $Layouts -split ","
$results = @()
$failures = 0

foreach ($layout in $LayoutList) {
    foreach ($mtp in @(0, 3)) {
        foreach ($label in $Prompts.Keys) {
            $prompt = $Prompts[$label]
            $maxCtx = $MaxCtxByLabel[$label]
            Write-Output "[validate_fusion] layout=$layout mtp=$mtp prompt=$label max-ctx=$maxCtx ..."
            $off = Invoke-Generation -layout $layout -prompt $prompt -mtp $mtp -disableEpilogue $true -maxCtx $maxCtx
            $on  = Invoke-Generation -layout $layout -prompt $prompt -mtp $mtp -disableEpilogue $false -maxCtx $maxCtx
            $hashOff = Get-Sha256Hex $off
            $hashOn  = Get-Sha256Hex $on
            $pass = ($hashOff -eq $hashOn)
            if (-not $pass) { $failures++ }
            $results += [pscustomobject]@{
                Layout = $layout; Mtp = $mtp; Prompt = $label
                FusionOffSha256 = $hashOff; FusionOnSha256 = $hashOn; Match = $pass
            }
            if (-not $pass) {
                Write-Output "  MISMATCH"
                Write-Output "  fusion off: $($off.Substring(0, [Math]::Min(200, $off.Length)))"
                Write-Output "  fusion on : $($on.Substring(0, [Math]::Min(200, $on.Length)))"
            } else {
                Write-Output "  OK ($hashOn)"
            }
        }
    }
}

Write-Output ""
Write-Output "[validate_fusion] summary:"
$results | Format-Table -AutoSize | Out-String | Write-Output

if ($failures -gt 0) {
    Write-Output "[validate_fusion] FAILED: $failures / $($results.Count) combinations diverged"
    exit 1
}
Write-Output "[validate_fusion] PASSED: $($results.Count) / $($results.Count) combinations byte-identical"
exit 0
